### PR TITLE
Add Metadata extraction and make this and the target size available for filters.

### PR DESCRIPTION
**Pull request by sbaechler**
I created a [filter for Thumbor](https://github.com/sbaechler/thumbor-universalimages) that adds the possibility for responsive art direction using the universal images XMP metadata standard.  An example of the filter output can be seen on the [demo page](http://sbaechler.github.io/universalimages-demo/).

For the filter to work I had to fork Thumbor and make some modifications to the BaseEngine and the Transformer classes. If the pyexiv2 library is available, then Thumbor extracts all metadata (not just Exif) from the image and stores it in the metadata property. Unfortunately, the Engine.__init__ method is the only place that has access to the original image metadata. Pillow strips it from the image data.

The filter needed the target size as well. I therefore added a getter method to the Transformer class and instantiated the class before the AFTER_LOAD filters are run. Those filter have access to the transformer instance and the target size.

This pull request solves issue #625.

There are two versions of the pyexiv2 library. The original one which is available for Python 2 (via homebrew or apt-get) and [py3exiv2](http://www.py3exiv2.tuxfamily.org/) for Python 3.

### CODE REVIEW

**Comment by guilhermef** [comment]
@sbaechler Travis is not running the tests with: [pyexiv2](https://travis-ci.org/thumbor/thumbor/jobs/108654298#L1569)

**Comment by sbaechler** [comment]
python-pyexiv2 and python py3exiv2 are not whitelisted in TravisCI yet. I opened a request for whitelisting them. This might take a while (usually about a week). I'll check back in a few days. Sorry for spamming the Slack channel, but the notification code is hardcoded in travis.yml.

**Comment by sbaechler** [comment]
TravisCI whitelisted python-pyexiv2 and the build is passing with the new library.
https://travis-ci.org/sbaechler/thumbor/jobs/109013961

Py3exiv2 is going to take a while longer because they have to whitelist the package repository first.

**Comment by jimas14** [comment]
@sbaechler How can pyexiv2 be available if py3 was introduced in thumbor v7?

**Comment by sbaechler** [comment]
@jimas14 This pull request was merged 5 years ago. At that time it worked. I haven't used thumbor recently.

**Comment by jimas14** [comment]
@sbaechler I understand, thanks for your response. I'm just confused how pyexiv2 was available at the time you merged this. When I try running the server with thumbor==6.7.0 and python==3.7 (so pyexiv2 can be installed) there are lots of version/syntax errors. And when I try running with thumbor==6.7.0 and python==2.7, pyexiv can't be installed due to version.

I'm trying to customize the engine init to allow IPTC to pass through, or at least copy some relevant IPTC fields into exif before returning. It's related to EU laws about copyright requirements. (https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038835832/2019-10-24%20%5blegifrance.gouv.fr%5d).

If you or @kkopachev have 10 mins to chat with me about this, I would greatly greatly greatly greatly appreciate it.

**Comment by sbaechler** [comment]
@jimas14 When I wrote the plugin, Thumbor was still at 6.0.0 and worked with Python 2.

I cannot remember it, but here is the readme for my plugin: https://github.com/sbaechler/thumbor-universalimages. It references Python 2 and Thumbor 6.0.0.

**Comment by jimas14** [comment]
@sbaechler I've seen that but didn't realize until today that `apt-get install python-pyexiv2` is how pyexiv2 is available with python 2.7

**Comment by sbaechler** [comment]
@jimas14 You are welcome.

I think I also got it to work with Python 3 since I asked Travis CI for whitelisting the Py3exiv2 package. I could however not find the code.

I did find my heroku project that thad the thumbor server configuration: https://github.com/sbaechler/thumbor-rmd-demo

**Pull request merged**
