### PR TITLE
Add transparent background support for filter 'round-corner'

### PR DESCRIPTION
**Pull request by AlterTable**
Issue: #412 

## Usage: ##

round_corner(a|b,r,g,b [,transparent])

## Arguments: ##

transparent - Optional. If set to true/1, the background will be transparent.

### CODE REVIEW

**Comment by heynemann** [comment]
Hey!!! Great PR! Thank you so much for it. Do you think you can also update the docs for the round_corner filter in the same PR? What about some tests for the round-corner filter? You can see an example at the [blur filter tests](https://github.com/thumbor/thumbor/blob/master/tests/filters/test_blur.py).

Once again, thank you for your contribution!

**Comment by heynemann** [comment]
LGTM. Let's wait for a bit to see what the other contributors think.

**Comment by heynemann** [comment]
Thank you very much for your contrib!

**Comment by AlterTable** [comment]
Thanks too for your reviews. 😄

**Pull request merged**
