### PR TITLE
add timings and counters for Smart and None Smart option

### PR DESCRIPTION
**Pull request by mohammedelhakim**

### CODE REVIEW

**Comment by heynemann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/heynemann/thumbor/pullRequest?prid=4967910&bid=16414093)

**Comment by heynemann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- thumbor/handlers/__init__.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/heynemann/thumbor/pullRequest?prid=4967910&bid=16414093)

**Comment by heynemann** [comment]
Lint has failed in your PR. Can you fix it please?

**Comment by heynemann** [comment]
Other than that, looks good to me.

**Comment by heynemann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- thumbor/handlers/__init__.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/heynemann/thumbor/pullRequest?prid=4967910&bid=16414093)

**Comment by softberry** [comment]
This change possibly introduces a braking issue for metrics usages :

I could not find the discussions on this issue and documentation about smart & none smart options. Could you please explain what is intended for those smart and none_smart options? Maybe I could implement that usage for my implementation to fix below explained bug.  

In my case, 
Sample usage of prometheus metrics with thumbor community plugin [tc_prometheus](https://github.com/thumbor-community/prometheus/blob/master/tc_prometheus/metrics/prometheus_metrics.py)

``` 
self.context.metrics.incr('response.smart')
self.context.metrics.timing('response.smart', total_time)
....
self.context.metrics.incr('response.none_smart')
self.context.metrics.timing('response.none_smart', total_time)
```
Above lines from from : [thumbor/handlers/__init__.py](https://github.com/thumbor/thumbor/pull/1251/files) are trying to create duplicate entry in CollectorRegistry which resulting following errors: 

```
ValueError: Duplicated timeseries in CollectorRegistry: 
{
        'thumbor_response_none__smart_created', 
        'thumbor_response_none__smart'
}
```

In all other implementations of `metrics.timing` and `metrics.incr` metric names are always different. For example:

```
        self.context.metrics.timing("response.time.{0}".format(status), total_time)
        self.context.metrics.incr("response.status.{0}".format(status))
```

**Pull request merged**
