### PR TITLE
Re-encode URL before validating HMAC to work around bad clients

### PR DESCRIPTION
**Pull request by banks**
As discussed on #598 this is an incomplete patch for the issue.

It's good enough for us for now so we will probably use this anyway but has issues noted in #598 that prevent this from being merged as it is. Lack of tests is one glaring issue.

It's shared as a PR for discussion.

### CODE REVIEW

**Comment by masom** [comment]
Tricky.

Thanks for looking into the issue and explaining the behaviour.

A major issue with old urls is thumbor allows something like `http://localhost:8000/unsafe/300x200/http://localhost/some/image.jpg`. It is somewhat not RFC compliant. The source url should always be encoded to something like `http://localhost:8000/unsafe/300x200/http%3A%2F%2Flocalhost%2Fsome%2Fimage.jpg`.

**Comment by heynemann** [comment]
@banks I think we are going in the direction @masom highlighted. We assume the URL is encoded and that's that. In the past we tried to be smart and every single time we got it wrong for some edge case. Now we are sticking by the RFC and it's working pretty well (as long as you encode the source URL, that is).

**Comment by banks** [comment]
Fair enough although note that #598 is NOT about source URL encoding. The comment in this PR even says clearly:

> Takes the raw URL and decodes any percent encoded characters that occur before the source URL starts.

So just enforcing that source URL is encoded is not a solution to the actual issue here.

This PR is dead either way and that's fine, just wanted to be clear that your stated rationale is a different issue entirely ;)

**Comment by heynemann** [comment]
Sorry for that. You are absolutely right.

**Pull request closed without merging**
