### PR TITLE
Watermark : Enable watermark centering and repeating, refs issue #545

### PR DESCRIPTION
**Pull request by adeboisanger**
Allow the value 'center' to be passed to the filter's parameters x or/and y in order to automatically center the filigrane.
ex : watermark(watermark.png,center,center,10)
watermark(watermark.png,10,center,10)
watermark(watermark.png,center,-10,10)

Allow the possibility to repeat the watermark horizontally or/and vertically by passing 'repeat' to x or/and y
example : filters:watermark(brasil_45.png,repeat,repeat,50)

### CODE REVIEW

**Comment by adeboisanger** [comment]
@guilhermef f***, it retained everything. 
I will copy all my code, recreate another fork and add my changes at once.
I will do it tomorrow. 
Thanks for all your help.

**Comment by guilhermef** [comment]
I'll try to do a merge squash.
Em 15/12/2015 12:18, "adeboisanger" <notifications@github.com> escreveu:

**Comment by guilhermef** [comment]
@adeboisanger I've managed to squash the merge: https://github.com/thumbor/thumbor/commit/84735839cb80a46c23e71f0842defdfec525b1d9

**Comment by adeboisanger** [comment]
@guilhermef Thank you so much !
Sorry for all the time you have spent on this issue.
If you come to Lyon, France, contact me, you deserve a beer (or two :p) !!

**Pull request closed without merging**
