### PR TITLE
Refactor code blocks for increased readability

### PR DESCRIPTION
**Pull request by scorphus**
Refactor code blocks for increased readability

Cues from pylint. Issues solved are as follows:

```
************* Module thumbor.config
thumbor/config.py:914:12: R1713: Consider using str.join(sequence) for concatenating strings from an iterable (consider-using-join)
************* Module thumbor.utils
thumbor/utils.py:92:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
************* Module tests.fixtures.transformer_test_data
tests/fixtures/transformer_test_data.py:79:8: W0719: Raising too general exception: Exception (broad-exception-raised)
```

This CL also fixes a code duplication issue in thumbor/utils.py

### CODE REVIEW

**Comment by scorphus** [comment]
The build is failing because of a codeclimate issue that I don't feel like fixing at this point.

**Comment by devppjr** [comment]
> The build is failing because of a codeclimate issue that I don't feel like fixing at this point.

@scorphus thanks for this PR, but this PR seems like https://github.com/thumbor/thumbor/pull/1566 of @guilhermef. This PR still make sense?

**Comment by scorphus** [comment]
I'm not sure. Prolly not relevant anymore. Maybe worth checking?

**Comment by scorphus** [comment]
Definitely not irrelevant. There are some nice fixes for some rather, arguably, nasty-looking code blocks 😁

**Comment by scorphus** [comment]
@devppjr, PR updated.

**Review by heynemann — APPROVED** [review]

**Comment by scorphus** [comment]
@devppjr, please hold on to this one as I've identified a couple more places for improvement.

**Comment by scorphus** [comment]
@sonarcloud wrote:
> [...]
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=thumbor_thumbor&pullRequest=1554) No Coverage information
> [](https://sonarcloud.io/component_measures?id=thumbor_thumbor&pullRequest=1554&metric=new_duplicated_lines_density&view=list) [0.3% Duplication](https://sonarcloud.io/component_measures?id=thumbor_thumbor&pullRequest=1554&metric=new_duplicated_lines_density&view=list)

I'd remedy that infliction as part of another PR but, as the codeclimate check [is failing](https://codeclimate.com/github/thumbor/thumbor/pull/1554), I'll have it here as well.

**Comment by scorphus** [comment]
Hey, @heynemann, would you kindly review it again?

**Review by devppjr — APPROVED** [review]

**Comment by devppjr** [comment]
hey @scorphus could you update your branch with master?

**Pull request merged**
