### PR TITLE
Prevent redis storage from crashing thumbor.

### PR DESCRIPTION
**Pull request by masom**
This PR add the `REDIS_STORAGE_IGNORE_ERRORS` configuration option to allow Thumbor to function if the redis instance becomes unreachable.

`on_exception` now delegates raising the exception to the error handler.

on_exception is also only used by redis: https://github.com/thumbor/thumbor/search?utf8=%E2%9C%93&q=on_exception

#### Default ( REDIS_STORAGE_IGNORE_ERRORS = False )
Current Thumbor behaviour:

```
2015-03-12 17:47:56 tornado.access:ERROR 500 GET /unsafe/80x80/filters:quality(80)/gif-1188749c-ed13-45b1-997d-8dc8a22b2df6.gif (127.0.0.1) 2.36ms
2015-03-12 17:47:56 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/Users/martin/venvs/thumbor/lib/python2.7/site-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/Users/martin/venvs/thumbor/lib/python2.7/site-packages/tornado/web.py", line 1503, in wrapper
    result = method(self, *args, **kwargs)
  File "/Users/martin/venvs/thumbor/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 100, in get
    self.check_image(kw)
  File "/Users/martin/venvs/thumbor/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 30, in check_image
    if self.context.modules.storage.exists(kw['image'][:self.context.config.MAX_ID_LENGTH]):
  File "/Users/martin/venvs/thumbor/lib/python2.7/site-packages/thumbor/utils.py", line 43, in wrapper
    exc_value
  File "/Users/martin/venvs/thumbor/lib/python2.7/site-packages/thumbor/storages/redis_storage.py", line 67, in on_redis_error
    raise exc_value
ConnectionError: Error 61 connecting localhost:6379. Connection refused.

2015-03-12 17:47:56 tornado.access:ERROR 500 GET /unsafe/80x80/filters:quality(80)/gif-1188749c-ed13-45b1-997d-8dc8a22b2df6.gif (127.0.0.1) 2.25ms
```

#### REDIS_STORAGE_IGNORE_ERRORS = True
```
2015-03-12 17:48:08 root:DEBUG thumbor running at 0.0.0.0:8888
2015-03-12 17:48:09 thumbor:WARNING Redis storage failure: Error 61 connecting localhost:6379. Connection refused.
2015-03-12 17:48:09 thumbor:WARNING Redis storage failure: Error 61 connecting localhost:6379. Connection refused.
2015-03-12 17:48:09 thumbor:DEBUG STATSD: storage.miss:1|c
2015-03-12 17:48:09 thumbor:DEBUG STATSD: original_image.status.200:1|c
2015-03-12 17:48:09 thumbor:WARNING Redis storage failure: Error 61 connecting localhost:6379. Connection refused.
2015-03-12 17:48:09 thumbor:DEBUG No image format specified. Retrieving from the image extension: .gif.
2015-03-12 17:48:09 thumbor:DEBUG Content Type of image/gif detected.
2015-03-12 17:48:10 tornado.access:INFO 200 GET /unsafe/80x80/filters:quality(80)/gif-1188749c-ed13-45b1-997d-8dc8a22b2df6.gif (127.0.0.1) 620.74ms
```

### CODE REVIEW

**Comment by masom** [comment]
Should the log level be error instead of warning?

**Comment by masom** [comment]
The Redis storage is using some kind of singleton instance preventing testing with pyvows.

**Comment by masom** [comment]
@guilhermef it seems unit tests are no longer executed. Should the tests be moved to integration_tests ?

**Comment by guilhermef** [comment]
@masom We've dropped the unit tests a while ago.
I think we just kept it for historical reasons, now all tests are on the vows folder.
It would be nice to have tests for this new behaviour.

**Comment by masom** [comment]
Would you know a way to execute vows synchronously? The redis storage keeps a class instance and when running as vows it fails due to the config changes required to test the behaviour.

**Comment by guilhermef** [comment]
@masom I think you could mock Storage.storage on a test or just replace it with a new instance.

**Comment by masom** [comment]
It seems like the only way to get the RedisStorage to cooperate inside vows is to allow not using a shared redis client.

The `RedisStorage` class has been updated to always fetch a "fresh" copy of the `storage` instance. This allow reconnecting to redis while processing a request.

Previous behaviour:
- `exists` fails
- `put` will be called but `storage` will be None.

New behaviour:
- `exists` fails
- `put` will reconnect to redis and maybe succeed ( vs failing completely )

**Comment by guilhermef** [comment]
thanks @masom 
I'll release a new version tomorrow.

**Pull request merged**
