### PR TITLE
Fix size px issue for SVG

### PR DESCRIPTION
**Pull request by alarchenko**
CairoSVG allows setting output image width and height, but they were unused. This caused issues with some SVG images in px units to be of very bad quality after conversion. [Example](https://assets.htmlacademy.ru/content/blog/113/svg/pikachu.svg) of such image will have 127x127 size after conversion, based on `viewBox="0 0 127.782 127.782"` of file.

This PR will allow us to set up the output px dimensions of input SVG images in all units.

### CODE REVIEW

**Comment by alarchenko** [comment]
@RaphaelVRossi @heynemann @guilhermef @scorphus Hello. Could someone please take a look? Thanks!

**Comment by RaphaelVRossi** [comment]
Hey @alarchenko ! Thanks for this contribution.

I'm testing your [example](https://assets.htmlacademy.ru/content/blog/113/svg/pikachu.svg) file.

In this case I don't see any difference between your code and Thumbor's master code.

Can you please, explain to me how to test with this file, and get some difference?

URL tested:
- `localhost:8888/unsafe/127x127/https://assets.htmlacademy.ru/content/blog/113/svg/pikachu.svg`
- `localhost:8888/unsafe/https://assets.htmlacademy.ru/content/blog/113/svg/pikachu.svg`

**Comment by alarchenko** [comment]
Hi @RaphaelVRossi. Thanks for the check. These two URLs will be without any difference, they match the size of viewbox. Please try this one: `localhost:8888/unsafe/1000x/https://assets.htmlacademy.ru/content/blog/113/svg/pikachu.svg`
This one in master will produce 127x127 image, but with changes it will be with desired size.
The difference should be look like this 
image

**Comment by RaphaelVRossi** [comment]
Nice catch @alarchenko 🎉

**Pull request merged**
