### PR TITLE
Configure GitHub Actions

### PR DESCRIPTION
**Pull request by scorphus**
<details><summary>Edit: This PR is ready to be reviewed and accepted.</summary>

~~**DRAFT PR!** I'm opening this to collect early reviews.~~

</details>

TravisCI has been great since Thumbor started back in the day. Nowadays, however, it's lagging. It takes longer and longer to have a build runner available. Some builds seem to take forever.

This PR aims at moving the build over to GitHub Actions. These are the required functionalities:

- [x] Python 3.6
- [x] Python 3.7
- [x] Python 3.8
- [x] Lint tests
- [x] Unit tests
- [x] Integration tests
- [x] Performance tests (Python 3.8 only)
- [x] Caching of dependencies
- [x] Coveralls integration
- ~~Slack integration~~ (can be done later)
- ~~? Failure allowance (probably for Python 3.9? Keep reading)~~ Fixed

<details><summary>Edit: The original workflow was simplified with the addition of another one, specific for performance/load tests.</summary>

Some features seem to be missing; others are not fully supported. ~~For example, I couldn't find a _readable_/_maintainable_ way to have different kinds of tests for different versions of Python. On the other hand, if we decide to have performance tests for all available versions, the `matrix` tree can be simplified.~~
</details>

<details><summary>Edit: Step conditionals are working great.</summary>

~~Another thing I'm still investigating is the step conditional. It didn't work at first attempts. For now, there's a workaround as part of the commands in `run` (e.g. `[[ "${{ matrix.python.test }}" != "PERF_TEST" ]] && exit 0`).~~
</details>

<details><summary>Edit: Python 3.9 is now part of the build too. \o/</summary>

~~Python 3.9 could be added too, but some dependencies like [opencv-python-headless](https://pypi.org/project/opencv-python-headless/#files) still don't provide wheels for 3.9, and the build either fails or takes forever only to fail again. We should keep an eye on upcoming [improvements](https://github.com/skvark/opencv-python/issues/382) — I've subscribed.~~
</details>

Merging this PR means the actions will run on every push and PR — just like you see below. Once we cover all our needs, we can — and should IMO — disable the build on Travis.

Any feedback is greatly appreciated.

Happy Halloween!

### CODE REVIEW

**Comment by scorphus** [comment]
Tests are failing for what should be at this time an obvious, expected reason: #1340

**Comment by heynemann** [comment]
Hey @scorphus! Let's work on this! I have finally gotten the testing docker image right! We can decrease drastically the build time here.

**Comment by scorphus** [comment]
Builds on GitHub Actions are not taking too longer than that. 2m30s is quite fast, IMHO.

I see a major issue. Whenever a PR either introduces a new dependency or fixes one — somehow like #1340 — the build might not serve its purpose.

There's also the addidional burden of always keeping those images up to date. On top of maintaining a packge we now would need to maintain a set of docker images.

I think we should merge this ASAP.

**Comment by scorphus** [comment]
Sorry, I misread the "New Dependency Introduction" bit.

Let's try and use those images.

**Comment by scorphus** [comment]
You did a stellar job on the images, @heynemann. As a big bonus the workflow is much simpler now.

Thank you!

**Pull request merged**
