### PR TITLE
Changing pyexiv2

### PR DESCRIPTION
**Pull request by heynemann**
Let's see if that can be done. Would make our docker image much smaller and not depend on boost.

### CODE REVIEW

**Comment by marcelometal** [comment]
there are some `py3exiv2` references

https://github.com/thumbor/thumbor/blob/f73aea633da026700004058bc35951320b020277/docs/metadata.rst

**Comment by heynemann** [comment]
Yeah gotta change the docs, but first I wanted to make sure tests are passing with the new pyexiv2... Seems to be the same thing.

**Comment by kkopachev** [comment]
metadata test was skipped because it could not import `ImageMetadata` class: https://github.com/thumbor/thumbor/runs/5008775364?check_suite_focus=true#step:7:239.
Not so easy :(

**Comment by heynemann** [comment]
That's odd, localy it's not skipping and apparently it exists in pyexiv2 https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md

**Comment by kkopachev** [comment]
@heynemann its ImageData vs Imagemetadata ne difference

**Pull request closed without merging**
