### PR TITLE
fix: ModuleNotFoundError: No module named 'setuptools'

### PR DESCRIPTION
**Pull request by Ronkiro**
Probably this fixes https://github.com/thumbor/thumbor/issues/1692 needs testing though

### CODE REVIEW

**Comment by marcelometal** [comment]
Root cause: https://github.com/docker-library/python/issues/952

**Comment by RaphaelVRossi** [comment]
Hey @Ronkiro thanks for contributing! :smile: 

I was testing it too, so maybe it's better if we install setuptools using [setup.py](https://github.com/thumbor/thumbor/blob/master/setup.py#L148). Either way, we need to install it to run it locally with Python 3.12. :thinking:

**Comment by RaphaelVRossi** [comment]
@Ronkiro Inside the `install_requires`. Something like: `"setuptools>=70.0.0",`

https://github.com/thumbor/thumbor/blob/5b19638385bc11b3aedfa6130a9a29438ab89b48/setup.py#L148

**Comment by Ronkiro** [comment]
@RaphaelVRossi  yeah, i mean, if we only do it we get an error because the code is tied to setuptools itself.

i.e. (the code below has setuptools inside `install_requires`)

```sh
python setup.py install
Traceback (most recent call last):
  File "C:\Programas\thinkai\trendy\gpt_job\setup.py", line 15, in <module>
    from setuptools import Extension, setup
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by RaphaelVRossi** [comment]
:thinking: but Thumbor's Makefile is using pip itself.

`python3 -m pip install -e .[tests]`

see: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#what-commands-should-be-used-instead

**Comment by Ronkiro** [comment]
I didn't know about that, ty! Closing for now

**Pull request closed without merging**
