### PR TITLE
print(), xrange(), unicode(), basestring, exception changes for Python 3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by masom** [comment]
@cclauss Could you fix the lint error about too many blank lines on `test_base64_hmac_sha1_signer.py` and squash into 1 commit?

**Comment by cclauss** [comment]
The GitHub web ui does not allow PR authors to squash multiple commits on repos that they do not have write access to.  It does however allow repo owners to do "__Squash and merge__" at the touch of a button.  https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits

**Comment by masom** [comment]
Gotcha, you are using the github web ui to make all those changes?

I don't mind squashing for you. You should know using the GitHub UI does create a repo + branch for you on your account: https://github.com/cclauss/thumbor/tree/patch-1

Once CI is green 🚀

**Comment by masom** [comment]
@cclauss I don't think https://github.com/thumbor/thumbor/pull/948/commits/2e533e9e886981b09f902051ecc6c6d805750bb4 should be applied.

Flake8 allows us to keep things consistent and match what the python community is expecting.

**Comment by cclauss** [comment]
Yes.  I did them all in the web ui.  I have tried before the use git at the command line to squash the repo + branch but it only led to frustration.  I need to pair program with a git guru someday.  If you could squash, that would be a great relief to me.

I you want to keep  2e533e9 in place, I have not objections.

**Comment by cclauss** [comment]
Ready for your review.

**Comment by masom** [comment]
Thank you @cclauss ! This is a first step toward Thumbor running on Python 3.3+

**Comment by cclauss** [comment]
Good stuff...  Python 3.3 goes [EOL](https://docs.python.org/devguide/index.html#branchstatus) next month you should probably shift up one to Python 3.4+.

**Comment by masom** [comment]
Yeah, but we currently don't even support python3 at all.

**Pull request merged**
