### PR TITLE
[FIX] Ability to listen to a socket passed as file descriptor

### LINKED ISSUE #1269: Trying to launch thumbor with a unix socket ends with "No such device or address"
Hi,

I'm trying to make thumbor listen to an Unix socket instead of port (and to automate this _via_ systemd but that's another story).

```shell
$ ls -al /run/thumbor/
total 0
drwxr-xr-x  2 root    root      60 Feb 23 15:51 .
drwxr-xr-x 27 root    root     880 Feb 23 15:18 ..
srw-rw-rw-  1 thumbor www-data   0 Feb 23 15:18 thumbor.sock

$ sudo -u thumbor /usr/local/bin/thumbor --fd /run/thumbor/thumbor.sock
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 147, in main
    server = run_server(application, context)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/server.py", line 118, in run_server
    with open(context.server.fd, 'r') as sock:
IOError: [Errno 6] No such device or address: '/run/thumbor/thumbor.sock'
```

A simple `/usr/local/bin/thumbor --fd /run/thumbor/thumbor.sock` ends the same, so I don't think it's a permission problem.

### Expected behaviour

The `--fd` option is announced to accept either a file descriptor or a path but it seems paths are not handled correctly.

I tried to use a simple file instead of a socket and ended with a "Bad file descriptor" error so I suppose the file has to be a socket. The `/run/thumbor/thumbor.sock` in my example has been created by systemd so I bet it's a valid Unix socket that should be supported out of the box.

I can see [a similar problems have been reported in the past](https://github.com/thumbor/thumbor/issues/929) but I can't use the same workaround as I'm not using Supervisor and the file descriptor for my socket will neither be 0 nor be predictible.

Am I missing something?

### PR DESCRIPTION
**Pull request by gael-ian**
Should fix #1269.

### CODE REVIEW

**Comment by gael-ian** [comment]
I realized today that not only AF_UNIX sockets can be passed as file descriptors. AF_INET / AF_INET6 sockets created by systemd, Supervisor or another orchestrator will be passed the same way to dependent services.

In Python 3.8, we could have used `socket(fileno=fd_number)` to turn any file descriptor to a proper socket object but thumbor runs with Python 2.7 and there's no such option on `socket()`.

Instead of trying to guess the correct family with some complex code, my proposition is to let users pass it as an argument and reuse the `--port` argument for this (as there no sense to pass a file descriptor and a port at the same time).

Hence a thumbor invocation would look like:

* `thumbor --fd /run/thumbor.sock` (AF_UNIX socket passed by path)
* `thumbor --fd 3 --port 1` (AF_UNIX socket passed by file descriptor)
* `thumbor --ip 127.0.0.1 --port 8080` (AF_INET socket)
* `thumbor --fd 3 --port 2` (AF_INET socket passed by file descriptor)
* `thumbor --ip ::1 --port 8080` (AF_INET6 socket)
* `thumbor --fd 3 --port 10` (AF_INET6 socket passed by file descriptor)

1, 2 and 10 are numeric values respectively associated to Python's socket `AF_UNIX`, `AF_INET` and `AF_INET6` constants.

**Comment by kkopachev** [comment]
Knowing to pass numbers is too magical? 

Another option to use https://github.com/tiran/socketfromfd which auto detects socket family and type.

**Comment by gael-ian** [comment]
> Another option to use https://github.com/tiran/socketfromfd which auto detects socket family and type.

Much more interesting than argument cycling, indeed. I change the pull request to use it.

**Comment by kkopachev** [comment]
That looks much cleaner, indeed. Would you fix the test please? Looks like it's trying to mock not existing anymore `socket`. That should now be `fromfd` mock instead

**Comment by gael-ian** [comment]
> Would you fix the test please?

Tomorrow. It's too late here to dig now into what are pip, virtualenv and the whole Python (2...) ecosystem.

**Comment by gael-ian** [comment]
Sorry, the history of this branch is a mess but I had to rely on TravisCi to run tests.

---

I tried to follow [contribution instructions](https://github.com/thumbor/thumbor/blob/master/CONTRIBUTING.md) but could not set up a development environment on my machine.

```shell script
$ python -V
Python 3.8.2
$ pip -V
pip 20.0.2
$ poetry --version
Poetry version 1.0.5
$ pip install -e .[tests]
[...]
ERROR: remotecv 3.0.0 has requirement Pillow<8.0.0,>=7.0.0, but you'll have pillow 6.2.2 which is incompatible.
$ make test                        
[... many failing tests ...]
make[1]: *** [Makefile:57: unit] Segmentation fault (core dumped)
make[1]: Leaving directory '[...]/thumbor'
make: *** [Makefile:39: test] Error 2
```

I noticed that, even on TravisCi, `remotecv` has unmet dependencies.

**Comment by kkopachev** [comment]
we should probably limit remotecv version to be below 3 for thumbor 6

**Comment by heynemann** [comment]
Should we cherry pick this to master?

**Comment by kkopachev** [comment]
We should. Not sure if python's `socket.socket(fileno=)` works as expected in all pythons 3.

**Comment by heynemann** [comment]
Do you mind cherry-picking it? If you can't, I'll find some time to do it.

Please be mindful of time spent here. **Your safety and getting your loved ones safe is the most important thing.** We can always work things out here later on! :) Hope you are safe and everyone you love as well.

**Pull request merged**
