### PR TITLE
[FEAT] Ability to run thumbor in multiprocess mode

### LINKED ISSUE #1275: [Feature] Add ability to run multiple processes
There should be ability to configure how many processes of thumbor should be running on startup. 
This would replace external solutions like supervisor/circus to manage thumbor processes.
This is built-in feature of tornado.
We could argue that app is asynchronous and should be just fine handling multiple requests at the same time, however there is GIL and blocking io (see file_storage). I have doubts that optimizers are fully async too.
In any case, even with fully async app, it still uses 1 CPU. There is no reason to not let user decide how many processes should be running on start.

[Docs on how to pass this to tornado](https://www.tornadoweb.org/en/stable/tcpserver.html#tornado.tcpserver.TCPServer.start)

/cc @gingerlime

### PR DESCRIPTION
**Pull request by kkopachev**
Closes #1275

### CODE REVIEW

**Comment by heynemann** [comment]
Do you mind also updating the docs on running thumbor?

**Comment by kkopachev** [comment]
Sure, I'll carve some time.

**Comment by heynemann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Clones removed
==============
+ tests/test_server.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/heynemann/thumbor/pullRequest?prid=5147974&bid=16909004)

**Comment by heynemann** [comment]
You know what? Let's ship this. It is good enough! We can update the docs later on.

**Comment by kkopachev** [comment]
Thanks, getting crazy with everything going on.

**Pull request merged**
