### PR TITLE
Bring back 'headers' context property as it is used by result storages

### PR DESCRIPTION
**Pull request by kkopachev**
Should fix https://github.com/thumbor/thumbor/pull/1003#issuecomment-365550122
@heynemann @bjoernhaeuser

### CODE REVIEW

**Comment by bjoernhaeuser** [comment]
I just tested this and the error is gone! looks good to me!

**Comment by heynemann** [comment]
Why did you remove the GC bit in the same PR?

**Comment by kkopachev** [comment]
@heynemann that was a piece remain after removing scheduled calls to gc.collect in previous PR https://github.com/thumbor/thumbor/pull/1003/files#diff-96c1f5e9855ad12779e42ade3a0c99e1L152

**Comment by heynemann** [comment]
Ok, LGTM

**Comment by heynemann** [comment]
Please test with master guys! Thanks for the hard work!

**Comment by bjoernhaeuser** [comment]
Tested master and looks good to me!

**Comment by bjoernhaeuser** [comment]
We will do more testing tomorrow. :)

**Comment by bjoernhaeuser** [comment]
Testing this no in production for a week and no new errors. Though I do not see the memory consumption to actually go done.

**Comment by kkopachev** [comment]
@bjoernhaeuser do you have mem consumption graphs before and after patch? Do you use tc_aws for some kind of storage?

**Comment by bjoernhaeuser** [comment]
Sorry, we do not have this data available. 

We are using tc_aws for retrieving source data from s3 and for s3 result storage.

**Comment by kkopachev** [comment]
@bjoernhaeuser I think that botocore is leaving circularly-referenced objects behind. I submitted an issue to tc_aws package to try to reuse same botocore clients over requests https://github.com/thumbor-community/aws/issues/109

**Pull request merged**
