### PR TITLE
fancy readme

### PR DESCRIPTION
**Pull request by mvhirsch**
Following #1388, every legendary project needs an awesome README.

Check it out:

* https://github.com/mvhirsch/thumbor/tree/fancy-readme#readme
* https://github.com/mvhirsch/thumbor/blob/fancy-readme/CONTRIBUTING.md

@heynemann I noticed you already updated the contributing guides. I just simplified it a bit.

### CODE REVIEW

**Comment by heynemann** [comment]
Do you mind fixing the weird <span> that's showing in redis in contributing.md?

**Comment by mvhirsch** [comment]
Sorry, but I can't see any issue. What do I need to fix?

**Comment by heynemann** [comment]
image

This is what I see when I go to contribution.md in your branch...

**Comment by mvhirsch** [comment]
Good catch, fixed! :+1:

**Pull request merged**
