### PR TITLE
Remove usage of shell=True

### PR DESCRIPTION
**Pull request by gi11es**
This is a security escalation vector (someone with edit rights for the
thumbor config could get arbitrary shell execution):

https://docs.python.org/3/library/subprocess.html#security-considerations

### CODE REVIEW

**Comment by masom** [comment]
Just an FYI but `(someone with edit rights for the
thumbor config could get arbitrary shell execution):` is true regardless of `shell=True`.

If someone can write to thumbor's configuration, it is possible to load a python file that can execute anything (ex: a filter that does `subprocess.Popen`)

**Comment by masom** [comment]
@gi11es I got a case of morning, didn't see the PR failed CI.

**Comment by gi11es** [comment]
I've just force-updated the commit on my fork, but I guess that doesn't work automatically when already merged. Do you prefer it this way, where you can run CI manually and force-update it here as well? Or as a follow-up commit fixing the issue (a missing comma)?

**Comment by gi11es** [comment]
As for the far-fetched scenario, in what you describe, wouldn't that require being able to write python files to thumbor's python environment? All those scenarios are pretty unlikely anyway, I've just fixed this because it was easy to make the code follow best practices this way.

**Comment by gi11es** [comment]
Ah, I see that you've already reverted, in that case I shall send a new PR.

**Pull request merged**
