### PR TITLE
Move integration tests out of the package

### PR DESCRIPTION
**Pull request by gi11es**
There's no reason to have integration tests installed when one installs thumbor.

### CODE REVIEW

**Comment by guilhermef** [comment]
I agree, @heynemann and @rfloriano ?

**Comment by heynemann** [comment]
I think they are included to make sure the tests pass. If the tests are passing without including them in the package, I'm fine with it.

**Comment by gi11es** [comment]
They do run and pass when outside of the package. You can see that in the Travis run right here: https://travis-ci.org/thumbor/thumbor/jobs/142688570

**Comment by guilhermef** [comment]
Thanks @gi11es

**Pull request merged**
