### PR TITLE
Send HTTP 400 if a watermark filter entity cannot be fetched, instead…

### PR DESCRIPTION
**Pull request by noamsml**
… of throwing an error

Otherwise an error will be thrown and a 500 will be sent back to the client.

### CODE REVIEW

**Comment by nerdrew** [comment]
Bump. Does someone from the thumbor project want to take a look at this?

**Comment by nerdrew** [comment]
@scorphus or @masom Can one of you take a look?

**Comment by masom** [comment]
@nerdrew Would it be possible to add a log message? https://github.com/thumbor/thumbor/pull/854#discussion_r101041666 was added 14 days ago.

**Comment by nerdrew** [comment]
@masom What kind of logs do you want?

Maybe:
```python
            logger.warn(
                    'bad watermark result error=%s metadata=%s' %
                    (result.error, result.metadata))
```

=>
```
thumbor: WARNING: bad watermark result error=not_found metadata={'updated_at': datetime.datetime(2016, 11, 28, 18, 6, 57), 'size': 1}
```

**Comment by scorphus** [comment]
This is absolutely better than failing with 500 👍  But I'm still wondering whether it's better to fail with 400 or just display the image with no watermark at all.

**Comment by scorphus** [comment]
As failing with 400 is, for most cases, the desired outcome, I'm merging this one. Thanks @noamsml and @nerdrew!

**Comment by kkopachev** [comment]
Unfortunately, that PR broke compatibility with aws loader. 
```
  File "/usr/local/lib/python2.7/site-packages/thumbor/filters/watermark.py", line 100, in on_fetch_done
    if not result.successful:
AttributeError: 'str' object has no attribute 'successful'
```
Since AWS loader for some reason just outputs bufferr, not wrapped in LoaderResult object:
https://github.com/thumbor-community/aws/blob/master/tc_aws/loaders/s3_loader.py#L112

**Comment by gingerlime** [comment]
@kkopachev we bumped into the same issue... (see #996). Shall we try to submit a PR? we're not too familiar with thumbor internals, but guess we can just make the check a bit more robust? Would appreciate any tips but this is currently breaking stuff for us on production :(

**Pull request merged**
