### PR TITLE
Allow configuring the gif engine.

### PR DESCRIPTION
**Pull request by masom**
Fixes https://github.com/thumbor/thumbor/issues/431

### CODE REVIEW

**Comment by masom** [comment]
Hopefully I didn't miss anything?

**Comment by guilhermef** [comment]
@masom looks good,
do you mind rebasing this PR ?

**Comment by masom** [comment]
@guilhermef rebased

**Comment by guilhermef** [comment]
Thanks @masom I'll just wait for travis, then merge and release a new version.

**Comment by masom** [comment]
@guilhermef I'm not sure what happened with the first rebase build. Somehow a test related to Mongo broke.

**Comment by guilhermef** [comment]
@masom I don't know what happens, sometimes the mongo tests break.

**Pull request merged**
