### PR TITLE
Same names for response.[none_]smart counters and timeseries cause exception in prometheus registry

### PR DESCRIPTION
**Pull request by mbarouski**
Having identical names for counters and time series metrics causes exception in Prometheus registry, so I suggest adding `.counter` and `.latency` postfixes for `response.smart` and `response.none_smart` metrics as Thumbor has in the rest of the codebase.

Also, I'm wondering if it's fine to have [`response.none_smart.count`](https://github.com/thumbor/thumbor/blob/master/thumbor/handlers/__init__.py#L132) and [`response.not_smart.count`](https://github.com/thumbor/thumbor/blob/master/thumbor/handlers/__init__.py#L96). They look similar by meaning but have different names. Maybe removal of one should be considered?

Original error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/thumbor/handlers/imaging.py", line 119, in get
    return await self.check_image(kw)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/thumbor/handlers/imaging.py", line 116, in check_image
    return await self.execute_image_operations()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/thumbor/handlers/__init__.py", line 133, in execute_image_operations
    self.context.metrics.timing("response.none_smart", total_time)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tc_prometheus/metrics/prometheus_metrics.py", line 54, in timing
    Metrics.summaries[name] = Summary(name, name, labels.keys())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/prometheus_client/metrics.py", line 143, in __init__
    registry.register(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'thumbor_response_none__smart_created', 'thumbor_response_none__smart'}
```

Identical names for counter and timeserie were added in this commit https://github.com/thumbor/thumbor/commit/d10ddbaa468ba7bb52461a0bfb38235d230d84f1#

### CODE REVIEW

**Comment by savar** [comment]
Right now it looks weird to have the `response.smart` being used in `def execute_image_operations()` in the first place. Why is that? Changing it (as this MR is trying) is actually now counting stuff probably twice per call (once going into the `execute_image_operations()` and once going into `on_finish()`) which is probably wrong. But why is it `response.*` inside `execute_image_operations()` in the first place?

**Comment by mbarouski** [comment]
@savar true, same question, maybe metrics I renamed should be removed at all 🤔

**Comment by mbarouski** [comment]
One more found

```
2022-07-04 19:19:39 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/thumbor/handlers/__init__.py", line 212, in get_image
    result = await self._fetch(self.context.request.image_url)
  File "/usr/local/lib/python3.9/site-packages/thumbor/handlers/__init__.py", line 805, in _fetch
    loader_result = await self.context.modules.loader.load(
  File "/usr/local/lib/python3.9/site-packages/thumbor_request_modifier/loader.py", line 42, in load
    return await http_loader.load(context, url)
  File "/usr/local/lib/python3.9/site-packages/thumbor/loaders/http_loader.py", line 212, in load
    return return_contents_fn(
  File "/usr/local/lib/python3.9/site-packages/thumbor/loaders/http_loader.py", line 86, in return_contents
    context.metrics.incr(
  File "/usr/local/lib/python3.9/site-packages/tc_prometheus/metrics/prometheus_metrics.py", line 46, in incr
    Metrics.counters[name] = Counter(name, name, labels.keys())
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/metrics.py", line 143, in __init__
    registry.register(self)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'thumbor_original__image_fetch_created', 'thumbor_original__image_fetch'}
```

**Comment by savar** [comment]
keep this open please as there was no answer yet..

**Comment by mbarouski** [comment]
> keep this open please as there was no answer yet..

**Comment by heynemann** [comment]
Can we fix the HTTP one as well?

**Comment by heynemann** [comment]
@mbarouski sorry for the long time in responding, but can we fix the other ones that are failing in this PR as well?

**Comment by mbarouski** [comment]
Hi @heynemann 
I fixed all which were failing at the moment I worked on it.

**Comment by mbarouski** [comment]
Hi @heynemann 👋🏻  Please close the PR or merge it :)

**Comment by savar** [comment]
Sure this should be closed?

**Review by heynemann — APPROVED** [review]

**Pull request merged**
