### PR TITLE
Remove SQS detection support

### PR DESCRIPTION
**Pull request by cristiandean**
Do we already have this feature in another project? If not, I think it would be a good idea to migrate it to [this one](https://github.com/thumbor/thumbor-aws/). 

I can do that if needed.

P.S. Do you think it would be better to mark the detector as @deprecated? So we could remove it after a while.

### CODE REVIEW

**Comment by heynemann** [comment]
Yes and yes :) thanks for helping out!

**Comment by heynemann** [comment]
I mean yes let's remove from thumbor into thumbor-AWS.

**Comment by heynemann** [comment]
Hey @cristiandean I think before removing we need to add it to thumbor-aws. What do you think?

**Comment by cristiandean** [comment]
@heynemann  Yeah, definitely! I'm working on this.

**Pull request closed without merging**
