### PR TITLE
Add config var to specify desired png compression

### PR DESCRIPTION
**Pull request by kkopachev**
I noticed this option is set for jpegs, so why not for png? 
Or the idea here to let people use optimizers after main transformations?

### CODE REVIEW

**Comment by guilhermef** [comment]
@kkopachev we should add ssim tests for this optimization.

**Comment by kkopachev** [comment]
Not sure we need that. `optimize` seems to only tell zip_encoder in pillow to compress harder. Since png is lossless in general. Pillow [does not do anything](https://github.com/python-pillow/Pillow/blob/a0602fb68c62ccf3825b7cd074751153772cef70/PIL/PngImagePlugin.py#L684) with image.
It just passes optimize flag [down to ZipEncoder](https://github.com/python-pillow/Pillow/blob/a0602fb68c62ccf3825b7cd074751153772cef70/PIL/PngImagePlugin.py#L771-L772) which [sets max compression level](https://github.com/python-pillow/Pillow/blob/d3727b523ece4f75def72bfc960e1abd104b5dcb/libImaging/ZipEncode.c#L77) 


Apart from that, looking at the pillow source, I think there is optimize option available for gif as well :grey_question:

**Comment by kkopachev** [comment]
New plan: instead of forcing max compression, expose config var. This is useful if people use more efficient optimizers after image operations. In case of PNG there is no reason to compress it, decompress and then compress it harder one more time.

**Comment by kkopachev** [comment]
Any updates here?

**Comment by kkopachev** [comment]
Guys, should I change something? Or explain a little more how that's useful?

**Comment by masom** [comment]
Thanks @kkopachev . We were expecting a difference in output but as you stated this compression happens at the file itself and is not lossy.

**Pull request merged**
