### PR TITLE
Add Thumbor official Docker image

### PR DESCRIPTION
**Pull request by guilhermef**
This image will be used to create the official helm chart.

### CODE REVIEW

**Review by heynemann — APPROVED** [review]
Great work as usual Gui!

**Comment by guilhermef** [comment]
@heynemann @RaphaelVRossi I made a small change in the release process to build using multiple Python versions of the Docker image and Thumbor's wheel.

**Review by RaphaelVRossi — APPROVED** [review]
LTGM 🚀 🎉

**Comment by p4sI** [comment]
Hi, will the official image be also available on Dockerhub? And if yes, when and under which docker repository?

**Comment by guilhermef** [comment]
Hi @p4sI, the image is here: https://hub.docker.com/r/thumbororg/thumbor

We release it in multiple registries: https://github.com/thumbor/thumbor/blob/master/.github/workflows/release.yml#L103

**Comment by mpdude** [comment]
Is this the new „official“ image? The documentation still mentions the `Minimalcompact/thumbor` image in a few places.

**Pull request merged**
