### PR TITLE
Asyncawait

### PR DESCRIPTION
**Pull request by heynemann**
Should not be merged yet.

### CODE REVIEW

**Comment by kkopachev** [comment]
I think it should not have conflicts at this point, since all my changes are already in master. They should not show up here. Rebase with skipping commits might help

**Comment by kkopachev** [comment]
I could do some things too, if you see a good way to split the work.

**Comment by heynemann** [comment]
There weren't any changes in master ever since I started this so I'll just force this into master. Will be easier then merging. If you'd like to take a go at merging, please go ahead :) The branch is in thumbor anyway :D

**Comment by heynemann** [comment]
Closing in favor of #1257.

**Pull request closed without merging**
