### PR TITLE
Allow result_storages to be asynchronous

### PR DESCRIPTION
**Pull request by masom**
The `result_storage` are currently using synchronous operations.

### CODE REVIEW

**Comment by Bladrak** [comment]
:+1:

**Comment by masom** [comment]
@heynemann Seems like we forgot the `result_storages` when moving to async `storages` :(

This should be backward-compatible.

**Comment by heynemann** [comment]
As soon as @guilhermef takes a look I'm fine with merging! Once again good job @masom

**Comment by guilhermef** [comment]
Looks good

**Pull request merged**
