### PR TITLE
Move Thumbor tests to run on host

### PR DESCRIPTION
**Pull request by guilhermef**
This will remove the need for separate Dockerfiles per Python version and simplify the test workflow.

### CODE REVIEW

**Comment by heynemann** [comment]
This is how it was previously. And every thumbor build took several minutes. After we started running tests in docker the builds started taking seconds. I'm all for improving the build, but time is key here. We can't have slow builds.

**Comment by guilhermef** [comment]
This change wouldn't impact the build times. We're already installing the build time dependencies on Docker during the action execution, but it will make it easier to cache.

**Comment by heynemann** [comment]
So we're once again taking long for building :/ How can we make builds fail in a couple seconds? Then if they succeed we update the docker images? That's why I added running tests in docker. Making it easier to contribute.

**Comment by guilhermef** [comment]
The whole test process takes around 2 minutes and, the environment setup takes less than 30 seconds.
It's a good trade-off since we would be able to validate that library updates aren't preventing Thumbor from being built.

**Pull request closed without merging**
