### PR TITLE
adding background_color filter to the default config

### PR DESCRIPTION
**Pull request by Savar**
this was accidentally missing when the filter was uploaded

### CODE REVIEW

**Comment by scorphus** [comment]
Thanks @Savar. Although [`fill`](http://thumbor.readthedocs.io/en/latest/filling.html#example-2) can do quite exactly what [`background_color`](http://thumbor.readthedocs.io/en/latest/background_color.html) does, I guess it's okay to have it and activate it by default.

**Comment by Savar** [comment]
@scorphus the issue with fill is, it changes the size whereas we want only to make the PNG file servable as JPG with a specific color used as filling for transparent areas. So thanks a lot!

**Comment by scorphus** [comment]
Actually, it doesn't 😃  Check this out:

Original:



With `filters:fill(purple,true)`:

http://localhost:8889/unsafe/filters:fill(purple,true)/https://raw.githubusercontent.com/thumbor/thumbor/f881643f1a50c71af926a95bba73ef9f09c0f098/docs/images/dice_transparent_background.png

dice_purple_background

**Comment by Savar** [comment]
yeah well.. you have to use the "fit-in" command with a bigger size than your original image :)

so try:

http://localhost:8889/unsafe/fit-in/2000x2000/filters:fill(purple,true)/https://raw.githubusercontent.com/thumbor/thumbor/f881643f1a50c71af926a95bba73ef9f09c0f098/docs/images/dice_transparent_background.png

**Comment by scorphus** [comment]
I'm not sure I got this quite right.

What good is `background_color` regarding the link you just wrote?

How different are the following two?

http://localhost:8888/unsafe/2000x2000/filters:fill(purple,true)/https://raw.githubusercontent.com/thumbor/thumbor/f881643f1a50c71af926a95bba73ef9f09c0f098/docs/images/dice_transparent_background.png

http://localhost:8889/unsafe/2000x2000/filters:background_color(purple)/https://raw.githubusercontent.com/thumbor/thumbor/f881643f1a50c71af926a95bba73ef9f09c0f098/docs/images/dice_transparent_background.png

**Comment by Savar** [comment]
? you ignored the 'fit-in' command:

http://localhost:8888/unsafe/fit-in/2000x2000/filters:fill(purple,true)/https://raw.githubusercontent.com/thumbor/thumbor/f881643f1a50c71af926a95bba73ef9f09c0f098/docs/images/dice_transparent_background.png

http://localhost:8889/unsafe/fit-in/2000x2000/filters:background_color(purple)/https://raw.githubusercontent.com/thumbor/thumbor/f881643f1a50c71af926a95bba73ef9f09c0f098/docs/images/dice_transparent_background.png

**Comment by Savar** [comment]
but actually I realize that we might missed one thing.. the `no_upscale` filter seems to create the same behavior in combination with `fill` but I have to re-check. Maybe it is worth to remove it again before releasing.

Please give me some time to re-evaluate that.

**Comment by Savar** [comment]
@scorphus it looks like we really missed that and it is probably interchangeable to do:

/unsafe/fit-in/1000x1000/filters:no_upscale():fill(color,true)/http://image/path.png
and
/unsafe/fit-in/1000x1000/filters:background_color(color)/http://image/path.png

so maybe we should remove background_color again? (also @masom)

**Comment by scorphus** [comment]
As I said, I think it's okay having the `background_color` filter and enabling it by default =)

**Comment by Savar** [comment]
My colleague found again the reason why we need background_color .. the `no_upscale()` only works properly if the image is smaller than what is requested in `fit-in` .. so

`/unsafe/fit-in/1000x1000/filters:no_upscale():fill(color,true)/http://image/big_2000x1500.png`
and
`/unsafe/fit-in/1000x1000/filters:background_color(color)/http://image/big_2000x1500.png`

will show why we need the background_color filter

**Pull request merged**
