### PR TITLE
Remove Url and Signer classes

### PR DESCRIPTION
**Pull request by gi11es**
They are now part of libthumbor.
Also removes the old url option and test,
as the related code was removed from libthumbor
some time ago.

### CODE REVIEW

**Comment by guilhermef** [comment]
Looks good.
What do you think @heynemann ?

**Comment by heynemann** [comment]
I don't think we can remove url signers. It will break compatibility with people who use different signers. I think @masom does, if I'm not mistaken.

**Comment by masom** [comment]
I think the changes are fine given it's a module rename. We'll just have to document that bc break.

**Comment by gi11es** [comment]
The CHANGELOG file looks pretty outdated, is that where you want the breaking change notice to go?

**Comment by guilhermef** [comment]
@gi11es we've abandoned this changelog file.
Now we use the releases page: https://github.com/thumbor/thumbor/releases

**Comment by gi11es** [comment]
Is there anything more I can do to help this PR get merged?

**Comment by guilhermef** [comment]
I had to revert your commit on 6.x branch to release 6.0.2, and fix #731.

**Comment by gi11es** [comment]
We could always import the classes in their old place for b/c

**Pull request merged**
