### PR TITLE
LastModified should be in UTC

### PR DESCRIPTION
**Pull request by Bladrak**
LastModified date should not depend on local timezones, this PR should fix it. However, this creates a BC Break with other result storages.

### CODE REVIEW

**Comment by masom** [comment]
Great find!

Should there be a test that ensures the TZ info is returned to the browser?

**Comment by Bladrak** [comment]
Maybe yes, I still need to figure out how to run thumbor's tests on my computer :) I'll try to add some.

**Comment by masom** [comment]
Poor @Bladrak :D ( we see all the builds on a slack channel )

**Comment by Bladrak** [comment]
Haha sorry to spam you, didn't manage to run the tests locally :(

**Comment by masom** [comment]
It's all good.

Yeah the local testing environment is a little bit hard to setup right now. We are removing a bunch of plugins from thumbor to make that process easier. No more mongodb / redis / memcache will greatly help with that.

**Comment by Bladrak** [comment]
Yup. I also noticed an issue with NFS sharing for the pil engine (given NFS is case insensitive, it confounds the import between the engine and the module). Maybe there's a rename to perform on the engine?

**Comment by masom** [comment]
I see. We might have to normalize engine names like `pil_engine`, `gif_engine`.

**Comment by Bladrak** [comment]
Yep, might be better :)

**Comment by Bladrak** [comment]
@masom \o/

**Comment by Bladrak** [comment]
@masom @heynemann could we have a release of thumbor so I can reference this fix as a dependency for the next ``tc_aws`` version?

**Comment by masom** [comment]
We're looking at thumbor 6...

There is also a 5.x branch we could backport this fix. We'll have to update all the storages to return UTC.

**Comment by Bladrak** [comment]
Yup you're right, thumbor 6 might be soon enough :) Do we know around when it will be released?

**Comment by heynemann** [comment]
I'm worried about releasing 6.0.0 due to URL encoding issues.

We need to work a little further on this.

**Pull request merged**
