### PR TITLE
Allow Pillow 5.1

### LINKED ISSUE #1038: Thinking about the future: Pillow 5
Recently, [Pillow 5.0 was released](https://github.com/python-pillow/Pillow/releases/tag/5.0.0) and testing it against Thumbor some tests failed. 

IMHO, in the near future Ubuntu and [Debian](https://packages.debian.org/sid/python-pil) will be released with Pillow 5, it would be great if it was fixed.

### PR DESCRIPTION
**Pull request by kkopachev**
Fixes #1038
@marcelometal @heynemann

### CODE REVIEW

**Comment by caeugusmao** [comment]
Hi @kkopachev,

What is the difference that you noted with this change? If we keep the same behavior, we can accept.

tks

**Comment by kkopachev** [comment]
@caeugusmao there are no functional difference as far as I can see.

**Comment by caeugusmao** [comment]
@kkopachev The building is not passing!! Could you verify before we accept?

Many tks!!!

**Comment by kkopachev** [comment]
@caeugusmao this should fix it: https://github.com/thumbor/thumbor/pull/1069

**Pull request merged**
