### PR TITLE
Implementing no_storage for result_storages.

### PR DESCRIPTION
**Pull request by cerber717**
Implementing no_storage for result_storages. I needed this because I do not want to store the results.

### CODE REVIEW

**Comment by cerber717** [comment]
https://github.com/thumbor/thumbor/issues/663

**Comment by guilhermef** [comment]
@cerber717 can you add some tests for the no_storage ?

**Comment by cerber717** [comment]
@guilhermef looks like unrelated test failed. Can you please look at it and possible merger it ?

**Comment by guilhermef** [comment]
@cerber717 that's the error: https://travis-ci.org/thumbor/thumbor/jobs/124533375#L2276
Th

**Comment by cerber717** [comment]
@guilhermef I added the test, and it looks fine. but the coverage did not reflect it. Any ideas why this might happen ?

**Comment by guilhermef** [comment]
@cerber717 the coverage is based on the folder /tests, but we still don't have storages tests there.

**Comment by guilhermef** [comment]
I'll migrate this test on the next release, It's ok for now

**Pull request merged**
