### PR TITLE
Fix resize causing transparency loss on paletted images

### LINKED ISSUE #987: Some transparent PNGs have black inserted as the background colour
### Thumbor request URL

Broken:
Original: https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld6878b91f
Resized: https://d32q3izcmhqbti.cloudfront.net/174x0/upld6878b91f

Working:
Original: https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld65b35218
Resized: https://d32q3izcmhqbti.cloudfront.net/174x0/upld65b35218

### Expected behaviour
Any transparent PNGs that are resized should have their backgrounds kept as transparent.

### Actual behaviour
Some are having black pixels inserted in place of transparent pixels.

### Operating system
OSx / Chrome

### Your thumbor.conf
Using through an AWS template, so don't have the config file handy.

### PR DESCRIPTION
**Pull request by kkopachev**
fixes #987 #945 #943

### CODE REVIEW

**Comment by cerber717** [comment]
👍

**Comment by kkopachev** [comment]
any news?

**Comment by jamiegwatkin** [comment]
Any news?

**Comment by cerber717** [comment]
:shipit:

**Comment by phunehehe** [comment]
This works! Merge please?

**Comment by heynemann** [comment]
Sorry guys and thank you very much for the PR... I'm in the middle of a very big life change (changing jobs, residency, kid's school...). I'm having a hard time keeping up and I'm very sorry for it. I'll pick up soon.

**Comment by onassar** [comment]
@heynemann no need to apologize. Thanks for all the work you're doing :-)

**Pull request merged**
