### PR TITLE
Remove usage of shell=True

### PR DESCRIPTION
**Pull request by gi11es**
This is a security escalation vector (someone with edit rights for the
thumbor config could get arbitrary shell execution):

https://docs.python.org/3/library/subprocess.html#security-considerations

### CODE REVIEW

**Comment by masom** [comment]
As soon CI passes this will be merged.

**Comment by gi11es** [comment]
Hah, yeah, by splitting untested code into more lines I've "decreased" coverage :)

**Comment by gi11es** [comment]
I'll try to add jpegtran coverage, just out of curiosity on how that can be done

**Comment by masom** [comment]
@gi11es  all checks have passed. Are you still looking at adding coverage?

**Comment by gi11es** [comment]
@masom I already did, the PR has been updated, jpegtran.py coverage is now 100%

**Comment by guilhermef** [comment]
This PR looks really good, but like @masom said, if someone has access to your thumbor.conf, they still can run arbitrary python code.

**Comment by gi11es** [comment]
Yeah, probably overkill, but it's probably better to have the code safer escaping-wise, as we don't know how people might extend it in the wild. This was flagged as "low risk" in our security team's review of Thumbor and we don't even use gifv not jpegtran at the moment. I just figured it wouldn't hurt to change it.

**Comment by gi11es** [comment]
And the good news for Thumbor is that's really all they could find in terms of "security issues" in their thorough review, the rest was simply configuration advice, which for the most part match the defaults.

**Comment by guilhermef** [comment]
We should probably add a warning somewhere in the docs about this thumbor.conf issue.

**Comment by gi11es** [comment]
Can you just throw python code in the .conf and it would run at startup?

**Comment by guilhermef** [comment]
Yes, that's how we load the thumbor.conf https://github.com/globocom/derpconf/blob/master/derpconf/config.py#L84

This way you can get the path or environment variables when it loads.

**Comment by gi11es** [comment]
Good to know. Is that common practice for python services/tornado apps?

**Comment by guilhermef** [comment]
A lot of python frameworks do this.
That's not really an issue, if someone gains root access to your production machine, messing with confs would be the last thing they would do.

**Comment by guilhermef** [comment]
@masom this PR looks really good, what do you think ?

**Comment by masom** [comment]
@guilhermef merge!

**Comment by guilhermef** [comment]
Thanks @gi11es

**Pull request merged**
