### PR TITLE
Include WebP files in MANIFEST.in

### PR DESCRIPTION
**Pull request by marcelometal**

### CODE REVIEW

**Comment by marcelometal** [comment]
> @marcelometal, what is the reasoning behind this change?

Since we are distributing the tests folder, we should include all the assets to run them.
Make sense? Feel free to close this MR if you think otherwise

**Comment by marcelometal** [comment]
> @marcelometal, what is the reasoning behind this change?

Since we are distributing the tests folder, we should include all the assets to run them.
Make sense? Feel free to close this MR if you think otherwise

**Comment by scorphus** [comment]
> > @marcelometal, what is the reasoning behind this change?
> 
> Since we are distributing the tests folder, we should include all the assets to run them. Make sense? Feel free to close this MR if you think otherwise

I don't mean to close it and I honestly have no thinking about it just yet. I'm trying to understand the reason really.

Another question to further understand things, it's already clear that I'm missing/forgetting something here 😆 Why do we ship Thumbor with tests?

**Comment by marcelometal** [comment]
> > > @marcelometal, what is the reasoning behind this change?
> > 
> > 
> > Since we are distributing the tests folder, we should include all the assets to run them. Make sense? Feel free to close this MR if you think otherwise
> 
> I don't mean to close it and I honestly have no thinking about it just yet. I'm trying to understand the reason really.
> 
> Another question to further understand things, it's already clear that I'm missing/forgetting something here laughing Why do we ship Thumbor with tests?

To validate RPM/Debian packages. It was added in "[Please add tests to the sdist](https://github.com/thumbor/thumbor/issues/1175)"

**Comment by scorphus** [comment]
> [...]
> To validate RPM/Debian packages. It was added in "[Please add tests to the sdist](https://github.com/thumbor/thumbor/issues/1175)"

I thought so. I guess I remember dealing with that while packaging Thumbor on Debian. Thanks for confirming.

**Review by scorphus — APPROVED** [review]
Nice catch then, @marcelometal 👍

**Pull request merged**
