### PR TITLE
Python 3 fixes

### PR DESCRIPTION
**Pull request by Tenzer**
Note: This PR is still WIP, I'm just making use of the Travis CI to run tests across multiple Python versions since I have problems running them locally. I hope that's okay.

I'm intending to try and move the support for Python 3 forwards as there currently are [issues blocked](https://github.com/thumbor/thumbor/issues/1039#issuecomment-440760670) by the lack of Python 3 support.

### CODE REVIEW

**Comment by Tenzer** [comment]
My first stumbling block is that on Python 3 the unit tests seg faults at the "tests.filters.test_background_color.BackgroundColorFilterTestCase" test. I have drilled this down to be caused by these lines of code:
https://github.com/thumbor/thumbor/blob/5b6e89c6a3154d409566466c2c0f11450726e549/thumbor/engines/pil.py#L375-L377

It calls code inside https://github.com/thumbor/thumbor/blob/master/thumbor/ext/filters/_composite.c, but here I come a bit short as my C coding skills are mostly non-existing, and especially with regards to Python bindings. If anybody with more knowledge in this area is able to look into it, that would be appreciated!

**Comment by heynemann** [comment]
Take a look at the refactor branch. It is python 3.7 and we have fixed some of the filters there.

**Comment by Tenzer** [comment]
Thanks for the pointer to that! Is there anywhere where the current status of that refactor can be tracked? Is the code in a state where it would be useful with some feedback from some production traffic hitting it?

**Comment by heynemann** [comment]
We are still missing some features that would allow for a real world usage. But as soon as we hit that we'll definitely let the community know. I plan on having a RC version that we can try as soon as possible.

**Comment by rht** [comment]
> We are still missing some features that would allow for a real world usage.

Is there a checklist of this? I can lend a hand for some of them.

**Comment by cristiandean** [comment]
@rht Yes, you can see here:
https://github.com/thumbor/thumbor/blob/refactor/README.mkd

**Pull request closed without merging**
