### PR TITLE
Execute imaging tasks in a thread pool

### PR DESCRIPTION
**Pull request by kevin1024**
This helps to avoid blocking the IOLoop when PIL starts hogging CPU

### CODE REVIEW

**Comment by kevin1024** [comment]
Ugh, looks like the thread pool kills the tests (the image operations are happening in another thread so the assertions all fail.

Possible solution: Disable the thread pool for testing.  Sound good?

**Comment by bjoernhaeuser** [comment]
I think disabling it for testing sounds good.

**Comment by guilhermef** [comment]
@kevin1024 this PR looks really good.
But don't you think that would be better to keep it backwards compatible ?
Keeping the default ENGINE_THREADPOOL_SIZE as 0 would set the thread_pool to None, and we start testing your solution as an experimental one.
What do you think ?

**Comment by kevin1024** [comment]
@guilhermef I think that's a great idea.  I'll make that change when I get a chance.

Also, the StatsD client isn't async so it can also block the IOLoop.  I just disabled on my servers it but it's really useful, so if I have time I'll try to look into making it asynchronous.  That would be in a separate pull request.  Let me know if that sounds interesting.

**Comment by kevin1024** [comment]
Oh, also the optimizers are not async.

**Comment by kevin1024** [comment]
OK, I did some refactoring and changed the default value to 0, disabling the threadpool by default.  Hopefully this will let the tests pass too.  Let's see!

**Comment by kevin1024** [comment]
It is probably worth mentioning that I'm using the default PIL backend.  Some backends may not be thread-safe.  PIL appears to be solid.

**Comment by kevin1024** [comment]
Hmm, I think I need to add a queue in front of the thread pool, in order to keep a full threadpool from blocking the IOLoop.

**Comment by guilhermef** [comment]
@kevin1024 It's looking good

**Comment by kevin1024** [comment]
Just an update, I found another spot that was blocking the IOLoop so I'm looking at throwing it in the thread pool as well.

**Comment by kevin1024** [comment]
OK I think this is working pretty well.  @masom can you test this out and see if it helps your use case?

**Comment by kevin1024** [comment]
oops hang on, found a bug...

**Comment by masom** [comment]
I'll be able to test tomorrow morning. I'll try to get some benchmarks of master, threadpool off and threadpool at 10

**Comment by kevin1024** [comment]
Cool, another variable for your benchmarks is `HTTP_LOADER_MAX_CLIENTS`.  That made a difference for me.

Also if you are using statsd it still blocks.  If I get some motivation I'll try to implement a nonblocking statsd client.

**Comment by kevin1024** [comment]
OK, fixed the aforementioned bug.  Should be good to go!

**Comment by masom** [comment]
@kevin1024 I might have hit a bug.

The first request that comes in seems to be blocking the entire IOLoop. ( doing a simple `os.system('sleep 30')` )

Subsequent requests seem to properly use the threadpool.

**Comment by masom** [comment]
@kevin1024 Found the reason. `os.sytem` blocks the GIL whereas `subprocess.call` does not.

**Comment by masom** [comment]
### Concurrency 10
`ab -n 100 -c 10`

#### 4.11.1 ( no threads )
```
Concurrency Level:      10
Time taken for tests:   17.547 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      1782100 bytes
HTML transferred:       1756600 bytes
Requests per second:    5.70 [#/sec] (mean)
Time per request:       1754.683 [ms] (mean)
Time per request:       175.468 [ms] (mean, across all concurrent requests)
Transfer rate:          99.18 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:   175 1675 292.4   1755    1799
Waiting:      175 1675 292.4   1755    1799
Total:        176 1675 292.4   1755    1799

Percentage of the requests served within a certain time (ms)
  50%   1755
  66%   1771
  75%   1776
  80%   1780
  90%   1793
  95%   1795
  98%   1798
  99%   1799
 100%   1799 (longest request)
```

#### ThreadPool-0
```
Concurrency Level:      10
Time taken for tests:   17.515 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      1782100 bytes
HTML transferred:       1756600 bytes
Requests per second:    5.71 [#/sec] (mean)
Time per request:       1751.469 [ms] (mean)
Time per request:       175.147 [ms] (mean, across all concurrent requests)
Transfer rate:          99.36 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:   172 1673 292.8   1756    1799
Waiting:      172 1673 292.8   1756    1799
Total:        172 1673 292.7   1756    1799

Percentage of the requests served within a certain time (ms)
  50%   1756
  66%   1766
  75%   1775
  80%   1779
  90%   1788
  95%   1793
  98%   1797
  99%   1799
 100%   1799 (longest request)
```

#### ThreadPool-10
```
Concurrency Level:      10
Time taken for tests:   6.671 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      1782100 bytes
HTML transferred:       1756600 bytes
Requests per second:    14.99 [#/sec] (mean)
Time per request:       667.084 [ms] (mean)
Time per request:       66.708 [ms] (mean, across all concurrent requests)
Transfer rate:          260.89 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:   409  657 122.8    648     994
Waiting:      361  572 123.5    560     958
Total:        409  657 122.8    648     995

Percentage of the requests served within a certain time (ms)
  50%    648
  66%    708
  75%    712
  80%    742
  90%    857
  95%    896
  98%    963
  99%    995
 100%    995 (longest request)
```

### Concurrency 20
`ab -n 100 -c 20`

#### 4.11.1

Same as concurrency 10

```
Concurrency Level:      20
Time taken for tests:   17.511 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      1782100 bytes
HTML transferred:       1756600 bytes
Requests per second:    5.71 [#/sec] (mean)
Time per request:       3502.166 [ms] (mean)
Time per request:       175.108 [ms] (mean, across all concurrent requests)
Transfer rate:          99.39 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       1
Processing:   171 3160 810.8   3481    3583
Waiting:      171 3160 810.8   3481    3583
Total:        172 3160 810.7   3482    3583

Percentage of the requests served within a certain time (ms)
  50%   3482
  66%   3491
  75%   3504
  80%   3512
  90%   3528
  95%   3559
  98%   3581
  99%   3583
 100%   3583 (longest request)
```

#### ThreadPool-0
```
Concurrency Level:      20
Time taken for tests:   17.604 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      1782100 bytes
HTML transferred:       1756600 bytes
Requests per second:    5.68 [#/sec] (mean)
Time per request:       3520.849 [ms] (mean)
Time per request:       176.042 [ms] (mean, across all concurrent requests)
Transfer rate:          98.86 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       1
Processing:   170 3182 817.6   3516    3584
Waiting:      170 3182 817.6   3515    3583
Total:        171 3182 817.5   3516    3584

Percentage of the requests served within a certain time (ms)
  50%   3516
  66%   3531
  75%   3539
  80%   3545
  90%   3554
  95%   3573
  98%   3582
  99%   3584
 100%   3584 (longest request)
```

#### ThreadPool-10
```
Concurrency Level:      20
Time taken for tests:   6.450 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      1782100 bytes
HTML transferred:       1756600 bytes
Requests per second:    15.50 [#/sec] (mean)
Time per request:       1290.097 [ms] (mean)
Time per request:       64.505 [ms] (mean, across all concurrent requests)
Transfer rate:          269.80 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.3      0       2
Processing:   399 1257 272.7   1247    1998
Waiting:      275 1098 251.3   1098    1899
Total:        399 1257 272.7   1247    1999

Percentage of the requests served within a certain time (ms)
  50%   1247
  66%   1394
  75%   1489
  80%   1489
  90%   1607
  95%   1641
  98%   1998
  99%   1999
 100%   1999 (longest request)
```

#### ThreadPool-20
```
Concurrency Level:      20
Time taken for tests:   6.419 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      1782100 bytes
HTML transferred:       1756600 bytes
Requests per second:    15.58 [#/sec] (mean)
Time per request:       1283.793 [ms] (mean)
Time per request:       64.190 [ms] (mean, across all concurrent requests)
Transfer rate:          271.12 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.8      0       7
Processing:   677 1252 214.2   1261    1896
Waiting:      604 1113 219.8   1115    1754
Total:        677 1252 214.2   1261    1897
WARNING: The median and mean for the initial connection time are not within a normal deviation
        These results are probably not that reliable.

Percentage of the requests served within a certain time (ms)
  50%   1261
  66%   1264
  75%   1281
  80%   1302
  90%   1312
  95%   1840
  98%   1887
  99%   1897
 100%   1897 (longest request)
```

**Comment by masom** [comment]
@kevin1024 Good job! The performance improvement is quite impressive.
My tests were using a small gif, ran through gifsicle and then through an ffmpeg optimizer.

#### Bug
Hitting `ctrl-c` in the shell running thumbor with the ThreadPoolExecutor enabled screws up something. The shell itself has to be reset:

image

**Comment by kevin1024** [comment]
@masom did you just replace the calls to `os.system` with `subprocess.call`?  I haven't seen that problem with the shell getting screwed up but I haven't been testing the optimizers much.  I wonder if some kind of stdout redirection is messing with your terminal.

**Comment by masom** [comment]
@kevin1024 We wrote our own Gifv optimizer to support a fork of gifsicle. We swapped `os.system` ( ) for `subprocess.call` due to  `os.system` locking the GIL.

Here's a simple test script to illustrate:

#### Subprocess.call

```python
from concurrent.futures import ThreadPoolExecutor
import random
import threading
import subprocess

pool = ThreadPoolExecutor(max_workers=10)

def sleepy():
    sleepytime= random.randint(0, 20)
    print("Sleeping: %s" % sleepytime)
    subprocess.call("sleep %s" % sleepytime, shell=True)
    print("Done sleeping for %s" % sleepytime)

for i in range(10):
    pool.submit(sleepy)

pool.shutdown()

print("ThreadPool ended")
```

#### os.system ( blocks )
```
import os
from concurrent.futures import ThreadPoolExecutor
import random
import threading

pool = ThreadPoolExecutor(max_workers=10)

def sleepy():
    sleepytime= random.randint(0, 20)
    print("Sleeping: %s" % sleepytime)
    os.system("sleep %s" % sleepytime)
    print("Done sleeping for %s" % sleepytime)

for i in range(10):
    pool.submit(sleepy)

pool.shutdown()

print("ThreadPool ended")
```

`os.system` will only execute synchronously  ( `ps aux | grep sleep` will show only 1 sleep ).

See https://github.com/thumbor/thumbor/blob/7900ac32709a3e4ddc2ccb25688aedd8f375c384/thumbor/optimizers/gifv.py#L31

**Comment by masom** [comment]
@kevin1024 as for the shell being messed up on ctrl-c it is something I can live with. The performance gain with the ThreadPool are quite noticeable at scale.

**Comment by kevin1024** [comment]
@masom  OK cool.  So the issue with the shell being messed up is unrelated to this pull request then, right?

**Comment by masom** [comment]
@kevin1024 Yep. Unrelated to this issue. Cheers!

**Comment by kevin1024** [comment]
OK I rebased since there were conflicts, and if Travis passes I think this should be good to merge.

**Comment by guilhermef** [comment]
@kevin1024 It's looking really good.
I just found a minor issue, on https://github.com/RealGeeks/thumbor/blob/threadpool/thumbor/handlers/__init__.py#L246

When you call self._write_results_to_client, It won't return after that call, so It will just follow and get called again on https://github.com/RealGeeks/thumbor/blob/threadpool/thumbor/handlers/__init__.py#L253

I don't think we have tests for this specific problem.

**Comment by guilhermef** [comment]
And I think you could add:
```python
cfg.ENGINE_THREADPOOL_SIZE = 10
```
to the https://github.com/RealGeeks/thumbor/blob/threadpool/thumbor/integration_tests/__init__.py#L31 file

This way we would at least run the integration tests with a threadpool.

**Comment by heynemann** [comment]
Completely agree with @guilhermef and would like to thank @kevin1024, @masom and @bjoernhaeuser for the awesome work you guys are doing. It helps everyone if we evolve thumbor.

I think this PR is moving in the right direction and with a few changes we'll merge and release it ASAP. What do you think @cezarsa?

**Comment by cezarsa** [comment]
This is really great. I agree that running integration tests with ENGINE_THREADPOOL_SIZE > 0 is desirable. LGTM aside from that.

**Comment by kevin1024** [comment]
Glad I could help, and thanks for Thumbor!

I made the changes as suggested.  Good catch with the storage results bug @guilhermef

**Comment by guilhermef** [comment]
Thank you @kevin1024, you're awesome!

**Comment by kevin1024** [comment]
:tada: :balloon:

**Pull request merged**
