### PR TITLE
Allow sending a `Access-Control-Allow-Origin` header

### PR DESCRIPTION
**Pull request by relthyg**
This commit takes #845 and adds tests and config support

Co-authored-by: Christian Green <christian@fanhero.com>

### CODE REVIEW

**Comment by mvhirsch** [comment]
Awesome work! I really like it!

@heynemann this should be merged. Could you please review it?

Please consider adding CORS headers on [Image Upload](https://thumbor.readthedocs.io/en/latest/how_to_upload_images.html), too. This way a client-based application could use the REST API, too. I'll create feature-request for it, after this got merged.

**Comment by heynemann** [comment]
I like it, but first a conflict must be fixed, and then @relthyg can you please add this to the docs?

**Comment by relthyg** [comment]
The merge conflict is solved and the docs are added, @heynemann . I wasn't quite sure to which section the docs for this option should be appended, so I put it after the SEND_IF_MODIFIED_LAST_MODIFIED_HEADERS docs, which is in the "Imaging" section. Feel free to give me a better position for this and I'll move it.

**Comment by heynemann** [comment]
That's odd, github still says that this has conflicts that must be solved, and because of that does not run tests...

**Comment by relthyg** [comment]
Conflict resolved.

**Comment by heynemann** [comment]
Released in both 7.x and 6.x versions of thumbor.

**Pull request merged**
