### PR TITLE
Jpegtran should preserve ICC profile if not forced to strip

### PR DESCRIPTION
**Pull request by kkopachev**

### CODE REVIEW

**Comment by Savar** [comment]
if you add to your pull request

```diff
diff --git a/tests/optimizers/test_jpegtran.py b/tests/optimizers/test_jpegtran.py
index bd716a3..eccc27a 100644
--- a/tests/optimizers/test_jpegtran.py
+++ b/tests/optimizers/test_jpegtran.py
@@ -11,7 +11,7 @@
 from os.path import abspath, join, dirname

 from thumbor.config import Config
-from thumbor.context import Context
+from thumbor.context import Context, RequestParameters
 from thumbor.optimizers.jpegtran import Optimizer
 from thumbor.utils import which

@@ -23,7 +23,9 @@ class JpegtranOptimizerTest(TestCase):
         conf = Config()
         conf.STATSD_HOST = ''
         conf.JPEGTRAN_PATH = which('jpegtran')
+        req = RequestParameters()
         ctx = Context(config=conf)
+        ctx.request = req
         optimizer = Optimizer(ctx)

         return optimizer
```
the tests would at least work again

**Comment by kkopachev** [comment]
@Savar thanks. Appreciate that. Applied patch.

**Comment by andreaugusto** [comment]
IMO the only thing that is missing in this PR is a test to ensure that the command will change if the strip_icc filter is in the request.

**Comment by kkopachev** [comment]
@andreaugusto done

**Comment by andreaugusto** [comment]
LGTM! Anyone wants to add/change anything on this PR?

//cc @scorphus, @masom, @Savar

**Comment by masom** [comment]
LGTM

**Comment by scorphus** [comment]
I believe the changes included in this PR should be bundled into a single commit. Does that make sense, @kkopachev? Would you mind us squashing your commits into one?

**Comment by andreaugusto** [comment]
It does make sense, @scorphus.

After the squash this PR is good to go.

**Comment by kkopachev** [comment]
@scorphus @andreaugusto all done

**Comment by andreaugusto** [comment]
Then again, thanks!

**Pull request merged**
