### PR TITLE
Updated pillow version due to security issues

### PR DESCRIPTION
**Pull request by heynemann**
Given pillow <9 has a security problem, let's take the opportunity and update pillow to the most recent version.

### CODE REVIEW

**Comment by heynemann** [comment]
Hmmm seems like we'll have to drop python 3.6 for that. Seems like a sensible choice anyway.

**Comment by mvhirsch** [comment]
> Hmmm seems like we'll have to drop python 3.6 for that. Seems like a sensible choice anyway.

Support for python 3.6 has ended last year. I too think this is a sensible choice.
https://www.python.org/dev/peps/pep-0494/#lifespan

**Comment by heynemann** [comment]
Maybe @kkopachev can help here? Any objections to moving to new pillow?

**Review by kkopachev — APPROVED** [review]
I think it's fine. We might want to release minor version for this change?

**Comment by heynemann** [comment]
Yep! 👍 Thanks!

**Comment by marcelometal** [comment]
https://github.com/thumbor/remotecv/blob/master/setup.py#L39
 https://github.com/thumbor/remotecv/pull/34

**Pull request merged**
