### PR TITLE
doctor: fix errors when there is no config

### PR DESCRIPTION
**Pull request by marcelometal**

### CODE REVIEW

**Comment by heynemann** [comment]
Hey good catch! Do you mind adding a test for when there's no config? I missed that one. There's a test file that tests doctor outputs.

**Review by heynemann — APPROVED** [review]
As mentioned above, pending only adding a unit test.

**Comment by heynemann** [comment]
Gotta fix another bug :( Sorry. There's a sys.exit if no errors found and that sys.exit should also respect the exit flag.

**Comment by heynemann** [comment]
Just need to update the snapshot and you should be good to go :)

**Comment by heynemann** [comment]
You force-pushed over my change :(

**Comment by heynemann** [comment]
Just remove the sys.exit from the print message method.

**Comment by marcelometal** [comment]
> You force-pushed over my change :(

I'm sorry!

> Just need to update the snapshot and you should be good to go :)

Did you add `--snapshot-update` in `make test`?

**Comment by heynemann** [comment]
Nope and you shouldn't, otherwise tests will never break. The idea of snapshots is that you look at the snapshot and it is what you expect, then it never changes (unless the functionality changes). This ensures the result is always the same.

**Pull request merged**
