### PR TITLE
Let engines do their own cleanup on application shutdown

### PR DESCRIPTION
**Pull request by gi11es**
I have a custom engine that relies on exiftool running as a daemon, getting commands from a named pipe. When Thumbor shuts down, I need to have this engine unlink the named pipe gracefully.

Suggestions on how to do that differently are welcome, I couldn't find any other way for my engine to be made aware of application shutdown.

### CODE REVIEW

**Comment by guilhermef** [comment]
That's a nice solution 👍

**Comment by guilhermef** [comment]
@heynemann @rfloriano What do you guys think ?

**Comment by heynemann** [comment]
The only thing missing is testing... Would be nice to have a test that proves that upon exit, thumbor cleans up after itself.

**Comment by gi11es** [comment]
I can add a test later today

**Comment by heynemann** [comment]
Awesome!!!

**Comment by gi11es** [comment]
Moved to #719 because of some mess on my own repo

**Pull request closed without merging**
