### PR TITLE
Make use of `MAX_SOURCE_SIZE` in the http_loader

### PR DESCRIPTION
**Pull request by hus787**

### CODE REVIEW

**Comment by masom** [comment]
@hus787 we cannot accept this PR as-is because it would break current behaviour.

Would it be possible to add a guard before applying the value and keep it with a default of 0?

Basically the argument to AsyncHttpClient would be optional if the value is > 0.

**Comment by andreaugusto** [comment]
Hi, @hus787! This is a needed PR since we are not using MAX_SOURCE_SIZE anywhere. Thanks! We'd like to merge it, but as @masom [asked](https://github.com/thumbor/thumbor/pull/826#issuecomment-279403602), could you:

1- Set the default value to 0 so that it does not break current behaviour. Right now it is unlimited.
2- Validate that ```MAX_SOURCE_SIZE < 0``` before using it.
3- Write a test for it.

**Comment by scorphus** [comment]
One needs to be very cautious while changing the default `http_loader` (as ell as any other default loader, storage, etc) as it may potentially introduce a breaking change.

**Comment by heynemann** [comment]
Any news here @hus787 ? Tests, defaults, documentation? Thanks!

**Comment by heynemann** [comment]
Closing this as this appears not to be moving forward.

**Pull request closed without merging**
