### PR TITLE
Remove unused python-magic dependency

### PR DESCRIPTION
**Pull request by gi11es**
No usage of that library found anywhere in the code

### CODE REVIEW

**Comment by gi11es** [comment]
No CI? :(

**Comment by guilhermef** [comment]
travis ?

**Comment by gi11es** [comment]
No idea what happened. I can't trigger a run manually from here, maybe you can?

**Comment by guilhermef** [comment]
You can try this: http://stackoverflow.com/a/36538741/1008783

**Comment by gi11es** [comment]
It works, thanks :) I didn't know about using "git commit --amend" like that, which is no-op but changes the commit hash.

**Comment by guilhermef** [comment]
Thanks @gi11es

**Pull request merged**
