### PR TITLE
Svg conversion png

### PR DESCRIPTION
**Pull request by rodrigolourenco**
Added support on Thumbor for svg conversion on png.

Using the Cairo (http://cairographics.org/) library with the python library CairoSVG (http://cairosvg.org/)  for conversion. Now, Thumbor was capable for doing this transparent verifying the mime type of the image and applying a conversion.

Sample: 
http://localhost:8888/unsafe/https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg

### CODE REVIEW

**Comment by guilhermef** [comment]
@rodrigolourenco It's better to keep cairoSVG outside the setup.py and only add svg support if carioSVG is available.

**Comment by rodrigolourenco** [comment]
@guilhermef Removed cairosvg from setup.py and checked if svg conversion to png is available.

**Comment by guilhermef** [comment]
@rodrigolourenco I need you to rebase this PR.

**Comment by rodrigolourenco** [comment]
@guilhermef done, PR updated.

**Comment by guilhermef** [comment]
thanks @rodrigolourenco

**Comment by znerol** [comment]
It seems to me that many SVGs start with an XML preabmble (i.e. `<?xml version="1.0" encoding="UTF-8"?>`) some also have a `DOCTYPE` declaration before the the SVG tag. Hence the magic sniffing code used here might fail to detect quite some files.

Example: https://upload.wikimedia.org/wikipedia/commons/b/b0/NewTux.svg

**Comment by znerol** [comment]
Relevant SO answer: https://stackoverflow.com/questions/15136264/how-can-i-say-a-file-is-svg-without-using-a-magic-number

**Comment by znerol** [comment]
SVG detection in Exiftool: https://sourceforge.net/p/exiftool/code/ci/master/tree/lib/Image/ExifTool/XMP.pm#l3732

**Comment by znerol** [comment]
Looks like these times it is safe to just look for an svg element with the proper namespace URL (https://phabricator.wikimedia.org/T43174), PR: #677

**Pull request merged**
