### PR TITLE
Librato test

### PR DESCRIPTION
**Pull request by seichner**

### CODE REVIEW

**Comment by seichner** [comment]
sorry, wrong repo for Merge Request...

**Comment by heynemann** [comment]
Where did you move this Pull Request to?

**Comment by seichner** [comment]
@heynemann we're still working on this internally (generic metrics for thumbro, with either the old statsd backend or an alternative librato backend), so i wanted to create a PR in our private repo. Its still WIP as you can see. I'll create a PR here once it's ready to present... ;-)

**Comment by phoet** [comment]
@seichner this is actually not private at all :smile_cat: https://github.com/Jimdo/thumbor/blob/master/thumbor/context.py#L36-L68

it's working good within our current setup and we are probably contributing a pluggable version by the end of this week.

screen shot 2015-08-03 at 10 59 52

**Pull request closed without merging**
