### PR TITLE
Yield coroutines

### PR DESCRIPTION
**Pull request by kkopachev**
Reason for these changes is that sometimes, when exception happens inside coroutine which was not yielded, it got trapped inside Future object for timeout (of 60 seconds) and request hangs for that time (since handler methods are `@asynchronous`)

Unyielded coroutines create other issues as well, like [inability to write a test for fail case ](https://github.com/thumbor/thumbor/pull/932)

Also, crossing fingers, that such change could help with memory leaks.

Also would be nice to have #894 merged before this one.

### CODE REVIEW

**Comment by kkopachev** [comment]
@heynemann what do you think of this going forward? Should I make it prettier and it could be merged? I noticed there are some activity on refactor branch, hence the question.

**Comment by heynemann** [comment]
I think we can accept this... I just didn't have time to try it. Did you take a look in the refactor branch? I am very interested in your opinion. I'm trying to fix some extensibility issues with thumbor. I'm having a hard time working on it, though.

**Comment by caeugusmao** [comment]
@kkopachev We can test this PR and it will be ok we accept . Could you integrate master with your branch first?

tks

**Comment by kkopachev** [comment]
So I rebased this. Not yet fully ready, though, but want to raise question to which branch it should go. I moved some stuff around, like moving imaging specific handler methods to imaging.py etc. So that might be BC break.

**Comment by heynemann** [comment]
Why do you think it would break BC? Did you change any external interfaces (storage, loader, engine, filter, etc) contracts (I will take a closer look as soon as possible)?

**Comment by heynemann** [comment]
Hey @kkopachev 

Really sorry we didn't integrate this yet. We are having a hard time here at globo.com so we couldn't spend our team time with thumbor lately.

Sorry again!

**Comment by heynemann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ thumbor/handlers/__init__.py  -8
+ thumbor/filters/__init__.py  -1
         

Clones removed
==============
+ tests/test_context.py  -4
+ tests/handlers/test_base_handler.py  -3
+ thumbor/filters/frame.py  -1
+ thumbor/filters/watermark.py  -1
+ tests/test_transformer.py  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/heynemann/thumbor/pullRequest?prid=4967915&bid=16414098)

**Comment by kkopachev** [comment]
closing in favor of #1257

**Pull request closed without merging**
