### PR TITLE
Add stretch parameter

### LINKED ISSUE #1123: Feature Request: stretch/scale to dimensions, disregarding aspect ratio
I want to be able to resize an image to exact dimensions, disregarding the image's aspect ratio (resize the image, without cropping).

With [Imgix](https://docs.imgix.com/apis/url/size/fit), this is done with `fit=scale`
https://assets.imgix.net/examples/kingfisher.jpg?fit=scale&h=200&w=900

Anything I try with Thumbor, it always seems to crop:
https:/[redacted]/900x200/filters:upscale()/examples/kingfisher.jpg

### PR DESCRIPTION
**Pull request by felipemsantana**
Closes #1123 

Using the image from the issue in the following URL:
http://localhost:8888/unsafe/stretch/900x200/assets.imgix.net/examples/kingfisher.jpg

Will output
image

TODO:
- [x] Add new parameter to https://github.com/thumbor/libthumbor (https://github.com/thumbor/libthumbor/pull/38)

### CODE REVIEW

**Comment by kenziedika** [comment]
how to enable this feature on my thumbor?

**Comment by kenziedika** [comment]
@felipemsantana or @heynemann can you help me how to enable this feature on my thumbor server?
im very need this feature

**Comment by caeugusmao** [comment]
Hi @felipemsantana,

The better approach in this case is transform the stretch feature in a pre load filter, you can be based on that filter here.

https://github.com/thumbor/thumbor/blob/b4096a957b8ea2420ea2d91818129dbc482c1ca6/thumbor/filters/focal.py

If we merge stretch feature as a new parameter in url, we have to make PR for all libs used to build thumbor urls and there are many of them, built in many languages.

Would you mind transform stretch in a filter?

tks,

**Comment by caeugusmao** [comment]
@kkopachev 

Maybe I have not been clear. We wouldn't like a new url pattern with new parameters because we should also update libs like https://github.com/thumbor/libthumbor. We do not see this need for this usage.

If we use stretch feature as a filter we will not impact this kind of lib. ;)

**Comment by kenziedika** [comment]
hello sir.

before, i'm use thumbor because thumbor have great performance than other image tool. but at this time i'm remove thumbor from my server and then use pilbox  [https://github.com/agschwender/pilbox ](https://github.com/agschwender/pilbox )this is because thumbor can't  stretch my image, and with pilbox i can stretch image very simple with scale rule.

i hope thumbor have this feature, in my case thumbor have many more great feature and performance, but thumbor don't have one feature that is "stretch" and for me this is critical.

**Comment by heynemann** [comment]
Hi @kenziedika 

I hope you find what you are looking for in pilbox and if you do, will you please write a comparison of your experience later on? That would help the whole community.

As for stretch, as soon as we are able to get it in our codebase without disrupting all thumbor's client libraries (in several different programming languages), we'll accept this PR.

**Comment by caeugusmao** [comment]
We add this feature as a filter using part of solution developed by @felipemsantana. PR #1134 

Thanks @felipemsantana

**Comment by timkelty** [comment]
Thanks @felipemsantana. Would you mind adding the stretch filter it to the docs?

**Comment by heynemann** [comment]
@timkelty this PR has not been merged. The PR that got merged is #1134  and that includes docs. Thanks for helping us improve Thumbor's community.

**Comment by timkelty** [comment]
Ah, thanks @heynemann.

Not seeing it here: https://thumbor.readthedocs.io/en/latest/filters.html

Do the docs just need to be regenerated/deployed?

**Comment by heynemann** [comment]
You are right, our docs hasn't been updated in a while. I'll fix it as soon as I can. The issue is the docs depend on thumbor to find its version, but readthedocs can't find thumbor since it's not installed.

**Pull request closed without merging**
