### PR TITLE
Fix Context object memory leak caused by circular references

### PR DESCRIPTION
**Pull request by kkopachev**
full explanation here: https://github.com/thumbor/thumbor/issues/753#issuecomment-341584293

### CODE REVIEW

**Comment by kkopachev** [comment]
I'd like some feedback on  this.
travis fails with style issues, which were not caused by changed lines in this pr.

**Comment by xiffy** [comment]
I'm testing these patches right now in production. And this definitely solves our memory leaking issue

**Comment by xiffy** [comment]
there still seems to be a bit of a memoryleak left, but the improvements are significant: https://imgur.com/a/9XGIt

**Comment by kkopachev** [comment]
@xiffy what loaders/storages do you use? I noticed s3 loader/storage leave a lot of collectable garbage after each request.

**Comment by xiffy** [comment]
We have exactly that ;-0 S3 (with 3 days worth of cache on disk local), and yes when loading from S3 is slow for whatever reason. memoryusage skyrockets. My hunch is that 599 / 504 leave some traces (and those are the hardest to test).

**Comment by kkopachev** [comment]
@heynemann is this possible to merge?

**Comment by heynemann** [comment]
Sorry for the long time to merge. The issue with merging this is that we'd have to test this. Do you think you can test this with the master branch once merged? If we could get the other people in this thread to test it I would have more confidence in creating a new release.

**Comment by ewhauser** [comment]
We regularly see the out of memory issue and can test this in production against significant traffic volumes.

**Comment by heynemann** [comment]
@ewhauser I'm merging this. I would love if you could test 6.4.1 before testing the master code. Since we feel it fixes the leak, it would be great to know for sure what fixed it.

**Comment by bjoernhaeuser** [comment]
I tested this together with tc-aws s3 result storage, it yields this error:

```
2018-02-14 10:37:58 tornado.application:ERROR Exception in callback <functools.partial object at 0x39f0890>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/src/thumbor/thumbor/handlers/__init__.py", line 468, in _store_results
    yield gen.maybe_future(result_storage.put(results))
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 483, in wrapper
    future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 471, in wrapper
    result = f(*args, **kwargs)
  File "/src/tc-aws/tc_aws/result_storages/s3_storage.py", line 42, in put
    super(Storage, self).set(bytes, path, callback=callback)
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 483, in wrapper
    future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 471, in wrapper
    result = f(*args, **kwargs)
  File "/src/tc-aws/tc_aws/aws/storage.py", line 72, in set
    metadata = dict(self.context.headers)
AttributeError: Context instance has no attribute 'headers'
```

**Comment by kkopachev** [comment]
I am going to look at this.

**Pull request merged**
