### PR TITLE
Allow loading of truncated images

### PR DESCRIPTION
**Pull request by kkopachev**

### CODE REVIEW

**Comment by kkopachev** [comment]
Any news here? Should I expose it as config param as well?

**Comment by masom** [comment]
👍 Looks good to me.

**Comment by masom** [comment]
@thumbor/contributors Should this be a configurable value? I don't really see why someone would want to have thumbor completely fail the operation if the source data is corrupted.

**Comment by rafaelcaricio** [comment]
Looks good to me. I would leave it as default until someone actually ask or need it to be configurable.

**Pull request merged**
