### PR TITLE
Fix for #739

### PR DESCRIPTION
**Pull request by paranpi**
encodes special characters, except: , / ? : @ & = + $ like javascript function encodeURI() in http loader

### CODE REVIEW

**Comment by guilhermef** [comment]
@paranpi The url should always be quoted, like: `http%3A%2F%2Ftest.com%2Fmaracuj%C3%A1.jpg`

**Comment by paranpi** [comment]
@guilhermef 
Encoded urls with special characters do not work with tornado.httpclient.AsyncHTTPClient.

For example, when I'm trying to use the following URL:
`https://raw.githubusercontent.com/thumbor/thumbor/master/tests/fixtures/images/maracujá.jpg`

Encoding the URL like this works  (only "á" is encoded),
`https://raw.githubusercontent.com/thumbor/thumbor/master/tests/fixtures/images/maracuj%C3%A1.jpg`

But this does not work (the entire URL, including ":" and "/" is encoded), in which case I get the response code 404.
`https%3A%2F%2Fraw.githubusercontent.com%2Fthumbor%2Fthumbor%2Fmaster%2Ftests%2Ffixtures%2Fimages%2Fmaracuj%C3%A1.jpg`

My pull request fixes this problem by allowing the URL to be encoded like the second one.
`https://raw.githubusercontent.com/thumbor/thumbor/master/tests/fixtures/images/maracuj%C3%A1.jpg '

**Comment by armanly** [comment]
Hi there @guilhermef 

I'm writing on behalf of Pagely. Thank you for making Thumbor :) we are big fans. Thank you @paranpi as well for putting this fix together...

We are running into the problem covered by this PR on one of our deployments and were wondering if there are plans to get this merged soon. We would prefer not to maintain our own fork and this looks like a good fix that would benefit anyone using Thumbor. 

Thanks in advance for your time!

Arman.

**Comment by guilhermef** [comment]
Hi @armanly, the ones taking care of Thumbor now are, @rfloriano and @masom.

**Comment by rfloriano** [comment]
Thanks @paranpi

**Pull request merged**
