### PR TITLE
Fixed unhandled "'NoneType' object has no attribute 'mode'" detector exceptions.

### PR DESCRIPTION
**Pull request by mvdklip**
Unhandled exceptions inside the face and feature detectors caused HTTP connections to hang and 'Future exception was never retrieved' tornado error messages to be logged. 

Example problem image:
http://s3-eu-west-1.amazonaws.com/nrcapp/cbf1017e5d2f798d48f5cf07bc428f0b12835e9e

This fix handles the exception by going to the next detector.

This problem only seems to occur when USE_GIFSICLE_ENGINE = True and when using the Metadata Endpoint.

### CODE REVIEW

**Comment by mvdklip** [comment]
Forgot to mention that the mentioned hangs only occur when using the Metadata Endpoint.

**Comment by guilhermef** [comment]
@mvdklip I'm not sure we need to schedule the garbage collector, what are you trying to fix with this ?

**Comment by mvdklip** [comment]
@guilhermef Not sure why these commits reference this PR. The original commit is: https://github.com/nrcmedia/thumbor/commit/c4eefea3e6acc90388a194f8a3c7d3d384dc76a6. Yesterday I ported some other commits to thumbor 6.x (master). The commit you're referencing is this: https://github.com/nrcmedia/thumbor/commit/59b0595da98fdf326f8b3c620c329a7f78c0a1bb, which is my fix for issue #753, but has nothing to do with this PR.

**Comment by mvdklip** [comment]
Just found this: http://stackoverflow.com/questions/11686435/how-to-stop-github-from-adding-new-commits-to-existing-pull-request
I was not aware that GH would automatically add all commits on that branch to my PR. Thought I needed to updat manually. Next time I'll create a separate feature branch.

**Comment by mvdklip** [comment]
Sorry for the mess. Closing this. Will create a new PR containing the original commit.

**Pull request closed without merging**
