### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by gabn88**
The rw flag is needed for changing the exif data (that is done in line 261 of this file). Otherwise this function fails with AttributeError.

### CODE REVIEW

**Comment by guilhermef** [comment]
@gabn88 can you create a test to validate this behavior ?

**Comment by gabn88** [comment]
I'd love to, but I'm not sure about my fix. It does seem to work (as in the AttributeError is gone), but I'm not so sure about the consequences...

**Comment by guilhermef** [comment]
I think that's the correct behavior, next time the changed image is read, It will have the right orientation.

**Comment by gabn88** [comment]
I tried to create a test, but I don't know how to start. Maybe just integrate this as it probably was just a type to do 'ro' instead of 'rw'?

**Comment by guilhermef** [comment]
@gabn88 can you post the steps to replicate the error ?

**Comment by gabn88** [comment]
While using a result storage, I set 'RESPECT_ORIENTATION' to True, then uploaded a picture with some exif orientation. 

Then the error came around.

**Comment by ptrln** [comment]
👍 thumbor has been broken for us due to this bug as well. we're getting a large number of thumbor crashes due to this error.

**Comment by r0bdiabl0** [comment]
Any update on this?

**Comment by guilhermef** [comment]
@gabn88 You can write a test based on https://github.com/thumbor/thumbor/blob/master/tests/handlers/test_upload_api.py#L65 but with RESPECT_ORIENTATION set to True and an image with exif

**Comment by fmunteanu** [comment]
@guilhermef, the correct behavior is ro or rw?

**Comment by guilhermef** [comment]
@fmunteanu It should be 'ro', since we're not changing the exif of the current image.
Thumbor creates a new Image.

**Comment by marcelometal** [comment]
Hi! I'm closing this issue because 'pexif' was replaced by 'piexif'.

Ref: 1d7f67c732a1a3c2088a2af3537c5fd4bbdb75c9

**Pull request closed without merging**
