### PR TITLE
Added Access-Control-Allow-Origin header to client response

### PR DESCRIPTION
**Pull request by Arthien**
Added CORS header in order to allow various HTML5 canvas functionality.

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

### CODE REVIEW

**Comment by aoqfonseca** [comment]
Why put this logical inside thumbor if you can do this with a reverse proxy in front of your thumbor server?
Can you put some tests for this new feature?

**Comment by Arthien** [comment]
This was added in order to make heroku deployments easier to manage.

**Comment by masom** [comment]
The config option needs to be added to the generator at https://github.com/thumbor/thumbor/blob/099685348de511ac7649574a9ee22935ab16ffb5/thumbor/config.py

**Comment by Savar** [comment]
@Arthien if it is worth it to import this, can you provide tests + the config change?

**Comment by Krato** [comment]
That will be very useful. Hope you merge it soon.

**Comment by heynemann** [comment]
Any news on the required changes?

* config support
* tests

**Comment by heynemann** [comment]
Closing this as this appears not to have moved forward.

**Comment by mpdude** [comment]
@heynemann If somebody comes up with a similar request again, adding tests and necessary documentation changes, would you merge it?

**Comment by heynemann** [comment]
Yes, I would!

**Pull request closed without merging**
