### PR TITLE
[WIP] implemented first attempt on keeping subsampling/qtables

### PR DESCRIPTION
**Pull request by seichner**
Still WIP (not configurable in thumbor.conf yet)

### CODE REVIEW

**Comment by seichner** [comment]
ok, made it configurable  via thumbor.conf, this also fixes the test.

**Comment by seichner** [comment]
refs https://github.com/thumbor/thumbor/issues/548

**Comment by heynemann** [comment]
@guilhermef any comments?

**Comment by guilhermef** [comment]
@seichner looking good ;)

**Comment by heynemann** [comment]
@seichner thank you very much for the contrib!

**Pull request merged**
