### PR TITLE
Watermark : Enable watermark centering, refs issue #545

### PR DESCRIPTION
**Pull request by adeboisanger**
Allow the value 'center' to be passed to  the filter's parameters x or/and y in order to automatically center the filigrane.
ex : watermark(watermark.png,center,center,10)
 watermark(watermark.png,10,center,10)
 watermark(watermark.png,center,-10,10) 

I don't know what I did wrong but the diff are not showing properly :
-        regex = r'(?:watermark\((?P<url>.*?),(?P<x>-?[\d]*?),(?P<y>-?[\d]*?),(?P<alpha>[\d]*?)\))'
+        regex = r'(?:watermark\((?P<url>.*?),(?P<x>(?:-?\d+)|center),(?P<y>(?:-?\d+)|center),(?P<alpha>[\d]*?)\))'

-        inv_x = self.x[0] == '-'		
-        inv_y = self.y[0] == '-'	
-        x, y = int(self.x), int(self.y)	
+        center_x = self.x == 'center'
+        center_y = self.y == 'center'
+        if not center_x :
+            inv_x = self.x[0] == '-'
+            x = int(self.x)
+        if not center_y :
+            inv_y = self.y[0] == '-'
+            y = int(self.y)

-        if inv_x:
-            x = (sz[0] - watermark_sz[0]) + x
-        if inv_y:
-            y = (sz[1] - watermark_sz[1]) + y
+        if center_x :
+            x = (sz[0] - watermark_sz[0]) /2
+        elif inv_x:
+            x = (sz[0] - watermark_sz[0]) + x        
+        if center_y :
+            y = (sz[1] - watermark_sz[1]) /2
+        elif inv_y:
+            y = (sz[1] - watermark_sz[1]) + y

-    @filter_method(BaseFilter.String, r'-?[\d]+', r'-?[\d]+', BaseFilter.PositiveNumber, async=True)
+    @filter_method(BaseFilter.String, r'(?:-?\d+)|center', r'(?:-?\d+)|center', BaseFilter.PositiveNumber, async=True)

### CODE REVIEW

**Comment by heynemann** [comment]
Do you think you can add some tests for this PR?

You can see an example test for the rotate filter [here](https://github.com/thumbor/thumbor/blob/master/vows/rotate_filter_vows.py).

I know the watermark filter does not have tests, but it would be great to improve thumbor's test coverage.

Other than the unit test, we must include it in the integration tests. [This is the file](https://github.com/thumbor/thumbor/blob/master/thumbor/integration_tests/urls_helpers.py) that defines all the available options for the test.

Thanks a lot for your contrib!

**Comment by adeboisanger** [comment]
Hi,

I am sorry, I am knew to Python (these are actually the first python’s lines that I wrote) and to open-source project contribution.
I don’t see how to write the test because there is no affectation of existing engine variables as in the rotate or quality filter.

I have added an entry in the urls_helper.py

Thank you.

Audran DE BOISANGER
Développeur Immovision



De : Bernardo Heynemann [mailto:notifications@github.com]
Envoyé : jeudi 17 septembre 2015 16:29
À : thumbor/thumbor
Cc : Audran DE BOISANGER
Objet : Re: [thumbor] Watermark : Enable watermark centering, refs issue #545 (#559)


Do you think you can add some tests for this PR?

You can see an example test for the rotate filter here<https://github.com/thumbor/thumbor/blob/master/vows/rotate_filter_vows.py>.

I know the watermark filter does not have tests, but it would be great to improve thumbor's test coverage.

Other than the unit test, we must include it in the integration tests. This is the file<https://github.com/thumbor/thumbor/blob/master/thumbor/integration_tests/urls_helpers.py> that defines all the available options for the test.

Thanks a lot for your contrib!

**Comment by adeboisanger** [comment]
I have just added the possibility to repeat the watermark horizontally or/and vertically by passing 'repeat' to x or/and y
example : filters:watermark(brasil_45.png,repeat,repeat,50)

**Comment by adeboisanger** [comment]
Hello Bernardo,
Do you know when the release which will include these changes to the watermark is supposed to come out ?
Thank you.

**Comment by imthehell** [comment]
Any news on the release date of this function?

**Comment by heynemann** [comment]
I'm very sorry, but we changed a LOT of stuff in thumbor. Can you rebase this PR to the latest changes? Also I still think you should include tests for this change. I have included test for most filters in the codebase now. Should be pretty simple to replicate one of the filter tests to verify this is working as expected.

**Comment by adeboisanger** [comment]
I have rebased my PR and I have added some unit tests, but they don't seem to be called as the code coverage test failed again.
I don't manage to pass the code coverage test.

**Comment by masom** [comment]
@heynemann something seems weird with coverage.

**Comment by guilhermef** [comment]
@adeboisanger When you run `make unit` does your tests run ?

**Comment by adeboisanger** [comment]
@guilhermef  Nope, I may need additionnal packages :

adeboisanger:~/thumbor$ sudo make unit
/bin/sh: 1: coverage: not found
make: *** [unit] Error 127

**Comment by guilhermef** [comment]
@adeboisanger you can run `make setup` to install everything

**Comment by adeboisanger** [comment]
Hi,
I wasn't able to build the unit tests, lots of missing dependancies on my VM.
Is there any news about the Code Coverage ?
Thank you.

**Comment by guilhermef** [comment]
@adeboisanger Your test aren't running.

**Comment by adeboisanger** [comment]
Thank you @guilhermef for the feedback.
Do you mean that they aren't being called or that they are not building/executing ?
I cannot find where to called them.
Thank you for your help.

**Comment by guilhermef** [comment]
I think I got it.
Your test file has an executable flag

rw-r--r--  1 guilhermef  staff   616B 26 Nov 15:19 /Users/guilhermef/projetos/home/thumbor/tests/filters/test_rgb.py

-rw-r--r--  1 guilhermef  staff   914B 26 Nov 15:19 /Users/guilhermef/projetos/home/thumbor/tests/filters/test_rotate.py

-rwxr-xr-x  1 guilhermef  staff   2,5K 10 Dez 11:45 /Users/guilhermef/projetos/home/thumbor/tests/filters/test_watermark.py

You have to run `chmod -x test_watermark.py`

**Comment by adeboisanger** [comment]
Thanks a lot @guilhermef !
Now I have to found why the similarity tests are failing.

**Comment by adeboisanger** [comment]
Sorry for bothering you again @guilhermef.
I don't get it.
I am using the same code for generating the fixtures' images  but I have only 74% of similarity.
Is there a way to see the images generated by the unit test ?
Thanks again.

**Comment by guilhermef** [comment]
Not on Travis, you would have to run it locally.

**Comment by guilhermef** [comment]
@adeboisanger Do you need help to get the generated images ?

**Comment by adeboisanger** [comment]
@guilhermef , it has been 3 months that I try to push this changes.
If you could help me this would be awesome.
To generate the images, I call my local thumbor branche using the parameters in the test file.
I have gained some similarity points by setting my local thumbor to save jpg with quality 100.
The issue is on the images with repeated watermarks.
Maybe there is another parameter using when the test is saving the generated images that I didn't set correctly in my thumbor.
I would really appreciate your help.
Thanks a lot !

**Comment by guilhermef** [comment]
@adeboisanger can you try to replace the source with an all white image ?

**Comment by guilhermef** [comment]
@adeboisanger You can add a self.debug(image) on your tests to see the generated image.
```
def test_watermark_filter_repeated_x(self):
        image = self.get_filtered('source100.jpg', 'thumbor.filters.watermark', 'watermark(watermark.png,repeat,center,70)')
        expected = self.get_fixture('watermarkRepeatX.jpg')
        self.debug(image)
        ssim = self.get_ssim(image, expected)
        expect(ssim).to_be_greater_than(0.99)
```

But I was running the tests here and it seems that the repeated watermark isn't working.

**Comment by guilhermef** [comment]
The problem is that the loader can't find the watermark.png file, you have
to configure the loader to be the file_loader.
Em 11/12/2015 11:51, "adeboisanger" <notifications@github.com> escreveu:

**Comment by guilhermef** [comment]
@adeboisanger You will have to add this to the FilterTestCase:
```
from os.path import exists, realpath, dirname, join

class FilterTestCase(PythonTestCase):
    _multiprocess_can_split_ = True

    def get_filter(self, filter_name, params_string="", config_context=None):
        config = Config(
            FILTERS=[filter_name],
            LOADER='thumbor.loaders.file_loader',
            FILE_LOADER_ROOT_PATH=join(dirname(realpath(__file__)), 'fixtures', 'filters')
        )
```

**Comment by adeboisanger** [comment]
@guilhermef Thanks a lot for everything !!
The unit tests had passed but I did lower the similarity expectation for the test_watermark_filter_repeated to 0.92
Is it acceptable ?
If it's ok, I will squash the commits.

**Comment by guilhermef** [comment]
@adeboisanger Actually, if I remove the watermark, the ssim gives me .92 of similarity, so the test won't be covering anything.

**Comment by adeboisanger** [comment]
@guilhermef This is weird.
So, can I squash the commits and say it's ok for production ?

**Comment by guilhermef** [comment]
Sure, I'll take a look at this after it's merged.

**Comment by adeboisanger** [comment]
@guilhermef Here we go :)
Is it good ?
Thanks

**Comment by guilhermef** [comment]
Sure, just squash the commits and I'll accept it.

**Comment by adeboisanger** [comment]
@guilhermef lol, that is what I though I did on my last commit.
I did a : git rebase -i HEAD~12 and sqash the last commits but I might have done something wrong ...

**Comment by guilhermef** [comment]
That's strange, github still shows as 27 commits

**Comment by adeboisanger** [comment]
I think I removed from the squash all commits preceding the last rebase I did on Nov 13, 2015.
I will try again :)

**Comment by adeboisanger** [comment]
@guilhermef :The last 4 commits are the good one. They contain all my changes.

**Comment by guilhermef** [comment]
That's really strange, github still shows 31 commits: https://github.com/thumbor/thumbor/pull/559/commits

**Comment by adeboisanger** [comment]
each time I try to I rebase to squash it had more commits, there is something that I don't see in this operation

**Comment by guilhermef** [comment]
Do you mind recreating the PR ?
Em 15/12/2015 12:04, "adeboisanger" <notifications@github.com> escreveu:

**Pull request closed without merging**
