### PR TITLE
Fix StatsD client so it doesn't do a lot of DNS lookups

### PR DESCRIPTION
**Pull request by kevin1024**
The DNS lookups in the StatsD client use a blocking getaddrinfo call.

This change keeps the instance of the StatsD client around so it won't
have to look up DNS over and over again, so it won't block the IOLoop.

Also cleaned up some whitespace in the ThumborStatsClient class.

### CODE REVIEW

**Comment by kevin1024** [comment]
If you guys merge this and my other pull request, I'll do another pull request to start sending some more stats, including:
 
  * Number of HTTP upstream workers queued (backlog)
  * Busy thread pool workers
  * Number of thread pool workers queued (backlog)

I think a total request time metric would be useful too.

**Comment by masom** [comment]
:+1:

**Comment by guilhermef** [comment]
Thank you @kevin1024 you're awesome

**Comment by kevin1024** [comment]
:cake:

**Pull request merged**
