### PR TITLE
adding new filter `upscale()` (fixes #726 and #856)

### LINKED ISSUE #726: Upscale and keeping ratio with the fill filter
### Thumbor request URL

[http://localhost:8888/unsafe/80x40/filters:fill(white,true)/http%3A//assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif](http://localhost:8888/unsafe/80x40/filters:fill%28white,true%29/http%3A//assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)

Original image: [Original image](http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)
### Expected behaviour

Hi, I am trying to get a thumbnail of an exact size of 80x40, that's why I use the fill filter. I use the fit-in parameter if the original image if bigger in width or length than 80x40. 

In this case the original image is 50x37, (it can be smaller or bigger than the requested width or length)

It should generate a 80x40 image but not cropped. In fact want I want is: [this](http://assets.kelformation.com/img/m/1/organismes/3672/logo_centre_3672_1.gif)
### Actual behaviour

Image is cropped and bottom and top parts of the original image are loosed, but its 80x40 as requested. if I use 0x40 the ratio is Ok but the image is 55x40 not 80x40.

[Wrong generated logo](https://thbr.figarocms.net/external/t5QLV0owiGWOjLx049eMFf3uzag=/80x40/filters:fill%28white,true%29/http%3A//assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)
### Operating system
- Ubuntu 14.04
- Thumbor 6.0.1

### PR DESCRIPTION
**Pull request by Savar**
upscale() works together with (adaptive-)fit-in like no_upscale()
together with either /WxH/ or (adaptive-)fit-in + filters:fill()

### CODE REVIEW

**Comment by Savar** [comment]
if this filter is accepted, then I would add the documentation to the pull request

**Comment by scorphus** [comment]
Go for it, @Savar!

**Comment by scorphus** [comment]
@Savar, I noticed a difference between these two:

[http://localhost:8888/unsafe/**fit-in**/80x40/filters:**fill**(white):**upscale**()/http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif](http://localhost:8888/unsafe/adaptive-fit-in/80x40/filters:fill(white):upscale()/http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)
not-upscaled
_(80x40)_


[http://localhost:8888/unsafe/**fit-in**/80x40/filters:**upscale**():**fill**(white)/http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif](http://localhost:8888/unsafe/adaptive-fit-in/80x40/filters:upscale():fill(white)/http://assets.kelformation.com/logos/organismes/3672/logo_centre_3672_1.gif)
upscaled
_(80x40)_

**Comment by Savar** [comment]
yeah that's normal thumbor `filter` behavior.. not all combination will work because it depends what was applied first..

example:
http://localhost:8888/unsafe/filters:blur(4):watermark(http://findicons.com/files/icons/1637/file_icons_vs_2/256/jpg.png,center,center,20)/https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg

jpeg_example_jpg_rip_100


http://localhost:8081/unsafe/filters:watermark(http://findicons.com/files/icons/1637/file_icons_vs_2/256/jpg.png,center,center,20):blur(4)/https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg
jpeg_example_jpg_rip_100 1

**Comment by Savar** [comment]
and `fill` also changes the image already inline.. so depending on "who comes first" the image will look different

**Comment by Savar** [comment]
@scorphus anything you think which needs to be changed?

**Comment by Savar** [comment]
??

**Comment by scorphus** [comment]
First of all, sorry for the delay and thanks for the contribution, @Savar.

> […] that's normal thumbor `filter` behavior […]

Sure, but I mean, at least on example regarding `fill` could be used in tests and added to the docs. What you think?

**Comment by Savar** [comment]
I'm fine to add documentation if you tell me where, I would suggest this text to be in the docs/filters.rst:

```
   .. ATTENTION::
    Filters are affecting each other in the order they are specified!
    So if you specify on an image with size ``60x40``

    ``fit-in/100x100/filters:watermark(..):blur(..):fill(red,1):upscale()/http://some/image.jpeg``

    then the image will first checked if it fits into ``100x100`` (which it does)
    gets the watermark, then it will be blurred (including the watermark), then
    filled with red so that it is using ``100x100`` so that at the end upscaled will
    be applied without any effect because fill was changing the size of the image
    already to the maximum available space.
```

but testing two filters one after another isn't really possible within the `get_filtered()` function and would need me to change a lot. And it was never tested for any of the other filters. Also what would you like to test? All different kind of behaviors in weird orders? I think it is fine to expect, that one filter is able to change the `result` image and will affect other filters?!

**Comment by Savar** [comment]
does that makes sense to you @scorphus ?

**Comment by Savar** [comment]
@scorphus ??

**Comment by scorphus** [comment]
Sorry again for such delay, things are always in a rush.

Apart from some grammar issues (e.g. `checked`) docs are good.

How about a test containing `fill` in the mix?

Good job, @Savar 👍 

Thanks!

**Comment by Savar** [comment]
I don't know how. The get_filterered stuff is only accepting one filter.. can you point me to the place you think it can be added?

**Comment by Savar** [comment]
I added the documentation now. But still don't see the point in testing multiple filter to see if the filter-chain works as expected. At least it would be a general test to see that the filter (with their different kind of stages like "PRE_LOAD", "AFTER_LOAD" and "POST_TRANSFROM") chain works as expected. Or better said: this has nothing to do with this specific filter and shouldn't be a requirement for this pull request to be merged.

**Comment by masom** [comment]
Let's get this merged and another PR can test that filter chaining works.

**Comment by Savar** [comment]
Perfect. I also think that this isn't related and should be done independently!

Am 27. April 2017 15:47:10 MESZ schrieb Martin Samson <notifications@github.com>:
>Let's get this merged and another PR can test that filter chaining
>works.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/pull/878#issuecomment-297717978

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Pull request merged**
